// @generated by protoc-gen-es v2.10.0 with parameter "target=ts,import_extension=none"
// @generated from file shared/v1/types.proto (package messageloop.shared.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file shared/v1/types.proto.
 */
export const file_shared_v1_types: GenFile = /*@__PURE__*/
  fileDesc("ChVzaGFyZWQvdjEvdHlwZXMucHJvdG8SFW1lc3NhZ2Vsb29wLnNoYXJlZC52MSJyCgdQYXlsb2FkEhQKDGNvbnRlbnRfdHlwZRgBIAEoCRInCgRqc29uGAIgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdEgAEhAKBmJpbmFyeRgDIAEoDEgAEg4KBHRleHQYBCABKAlIAEIGCgRkYXRhInkKCE1ldGFkYXRhEj0KB2VudHJpZXMYASADKAsyLC5tZXNzYWdlbG9vcC5zaGFyZWQudjEuTWV0YWRhdGEuRW50cmllc0VudHJ5Gi4KDEVudHJpZXNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBQklaR2dpdGh1Yi5jb20vbWVzc2FnZWxvb3Bpby9tZXNzYWdlbG9vcC9zaGFyZWQvZ2VucHJvdG8vc2hhcmVkL3YxO3NoYXJlZHBiYgZwcm90bzM", [file_google_protobuf_struct]);

/**
 * 统一的数据载荷类型
 *
 * @generated from message messageloop.shared.v1.Payload
 */
export type Payload = Message<"messageloop.shared.v1.Payload"> & {
  /**
   * 数据内容类型 (e.g., "application/json", "text/plain", "application/octet-stream")
   *
   * @generated from field: string content_type = 1;
   */
  contentType: string;

  /**
   * @generated from oneof messageloop.shared.v1.Payload.data
   */
  data: {
    /**
     * JSON 对象，编码时可读
     *
     * @generated from field: google.protobuf.Struct json = 2;
     */
    value: JsonObject;
    case: "json";
  } | {
    /**
     * 二进制数据
     *
     * @generated from field: bytes binary = 3;
     */
    value: Uint8Array;
    case: "binary";
  } | {
    /**
     * 文本数据
     *
     * @generated from field: string text = 4;
     */
    value: string;
    case: "text";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message messageloop.shared.v1.Payload.
 * Use `create(PayloadSchema)` to create a new message.
 */
export const PayloadSchema: GenMessage<Payload> = /*@__PURE__*/
  messageDesc(file_shared_v1_types, 0);

/**
 * 统一的元数据类型
 *
 * @generated from message messageloop.shared.v1.Metadata
 */
export type Metadata = Message<"messageloop.shared.v1.Metadata"> & {
  /**
   * @generated from field: map<string, string> entries = 1;
   */
  entries: { [key: string]: string };
};

/**
 * Describes the message messageloop.shared.v1.Metadata.
 * Use `create(MetadataSchema)` to create a new message.
 */
export const MetadataSchema: GenMessage<Metadata> = /*@__PURE__*/
  messageDesc(file_shared_v1_types, 1);

