// @generated by protoc-gen-es v2.10.0 with parameter "target=ts,import_extension=none"
// @generated from file shared/v1/types.proto (package messageloop.shared.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file shared/v1/types.proto.
 */
export const file_shared_v1_types: GenFile = /*@__PURE__*/
  fileDesc("ChVzaGFyZWQvdjEvdHlwZXMucHJvdG8SFW1lc3NhZ2Vsb29wLnNoYXJlZC52MSJMCgdQYXlsb2FkEicKBGpzb24YASABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0SAASEAoGYmluYXJ5GAIgASgMSABCBgoEZGF0YSJ5CghNZXRhZGF0YRI9CgdlbnRyaWVzGAEgAygLMiwubWVzc2FnZWxvb3Auc2hhcmVkLnYxLk1ldGFkYXRhLkVudHJpZXNFbnRyeRouCgxFbnRyaWVzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4AUJJWkdnaXRodWIuY29tL21lc3NhZ2Vsb29waW8vbWVzc2FnZWxvb3Avc2hhcmVkL2dlbnByb3RvL3NoYXJlZC92MTtzaGFyZWRwYmIGcHJvdG8z", [file_google_protobuf_struct]);

/**
 * 统一的数据载荷类型
 *
 * @generated from message messageloop.shared.v1.Payload
 */
export type Payload = Message<"messageloop.shared.v1.Payload"> & {
  /**
   * @generated from oneof messageloop.shared.v1.Payload.data
   */
  data: {
    /**
     * JSON 对象，编码时可读
     *
     * @generated from field: google.protobuf.Struct json = 1;
     */
    value: JsonObject;
    case: "json";
  } | {
    /**
     * 二进制数据
     *
     * @generated from field: bytes binary = 2;
     */
    value: Uint8Array;
    case: "binary";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message messageloop.shared.v1.Payload.
 * Use `create(PayloadSchema)` to create a new message.
 */
export const PayloadSchema: GenMessage<Payload> = /*@__PURE__*/
  messageDesc(file_shared_v1_types, 0);

/**
 * 统一的元数据类型
 *
 * @generated from message messageloop.shared.v1.Metadata
 */
export type Metadata = Message<"messageloop.shared.v1.Metadata"> & {
  /**
   * @generated from field: map<string, string> entries = 1;
   */
  entries: { [key: string]: string };
};

/**
 * Describes the message messageloop.shared.v1.Metadata.
 * Use `create(MetadataSchema)` to create a new message.
 */
export const MetadataSchema: GenMessage<Metadata> = /*@__PURE__*/
  messageDesc(file_shared_v1_types, 1);

