// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: server/v1/api.proto

package serverpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Publication struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Destination   *Publication_Destination `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Options       *Publication_Options     `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	PayloadBlob   []byte                   `protobuf:"bytes,4,opt,name=payload_blob,json=payloadBlob,proto3" json:"payload_blob,omitempty"`
	PayloadText   string                   `protobuf:"bytes,5,opt,name=payload_text,json=payloadText,proto3" json:"payload_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Publication) Reset() {
	*x = Publication{}
	mi := &file_server_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Publication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publication) ProtoMessage() {}

func (x *Publication) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publication.ProtoReflect.Descriptor instead.
func (*Publication) Descriptor() ([]byte, []int) {
	return file_server_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *Publication) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Publication) GetDestination() *Publication_Destination {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *Publication) GetOptions() *Publication_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Publication) GetPayloadBlob() []byte {
	if x != nil {
		return x.PayloadBlob
	}
	return nil
}

func (x *Publication) GetPayloadText() string {
	if x != nil {
		return x.PayloadText
	}
	return ""
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Publications  []*Publication         `protobuf:"bytes,3,rep,name=publications,proto3" json:"publications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_server_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *PublishRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PublishRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PublishRequest) GetPublications() []*Publication {
	if x != nil {
		return x.Publications
	}
	return nil
}

type PublishReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishReply) Reset() {
	*x = PublishReply{}
	mi := &file_server_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishReply) ProtoMessage() {}

func (x *PublishReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishReply.ProtoReflect.Descriptor instead.
func (*PublishReply) Descriptor() ([]byte, []int) {
	return file_server_v1_api_proto_rawDescGZIP(), []int{2}
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_server_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_api_proto_rawDescGZIP(), []int{3}
}

type DisconnectReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectReply) Reset() {
	*x = DisconnectReply{}
	mi := &file_server_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectReply) ProtoMessage() {}

func (x *DisconnectReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectReply.ProtoReflect.Descriptor instead.
func (*DisconnectReply) Descriptor() ([]byte, []int) {
	return file_server_v1_api_proto_rawDescGZIP(), []int{4}
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_server_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_api_proto_rawDescGZIP(), []int{5}
}

type SubscribeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeReply) Reset() {
	*x = SubscribeReply{}
	mi := &file_server_v1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeReply) ProtoMessage() {}

func (x *SubscribeReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeReply.ProtoReflect.Descriptor instead.
func (*SubscribeReply) Descriptor() ([]byte, []int) {
	return file_server_v1_api_proto_rawDescGZIP(), []int{6}
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_server_v1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_api_proto_rawDescGZIP(), []int{7}
}

type UnsubscribeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeReply) Reset() {
	*x = UnsubscribeReply{}
	mi := &file_server_v1_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeReply) ProtoMessage() {}

func (x *UnsubscribeReply) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeReply.ProtoReflect.Descriptor instead.
func (*UnsubscribeReply) Descriptor() ([]byte, []int) {
	return file_server_v1_api_proto_rawDescGZIP(), []int{8}
}

type Publication_Options struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddHistory    bool                   `protobuf:"varint,1,opt,name=add_history,json=addHistory,proto3" json:"add_history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Publication_Options) Reset() {
	*x = Publication_Options{}
	mi := &file_server_v1_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Publication_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publication_Options) ProtoMessage() {}

func (x *Publication_Options) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publication_Options.ProtoReflect.Descriptor instead.
func (*Publication_Options) Descriptor() ([]byte, []int) {
	return file_server_v1_api_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Publication_Options) GetAddHistory() bool {
	if x != nil {
		return x.AddHistory
	}
	return false
}

type Publication_Destination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []string               `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Channels      []string               `protobuf:"bytes,2,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Publication_Destination) Reset() {
	*x = Publication_Destination{}
	mi := &file_server_v1_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Publication_Destination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publication_Destination) ProtoMessage() {}

func (x *Publication_Destination) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publication_Destination.ProtoReflect.Descriptor instead.
func (*Publication_Destination) Descriptor() ([]byte, []int) {
	return file_server_v1_api_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Publication_Destination) GetSessions() []string {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *Publication_Destination) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

var File_server_v1_api_proto protoreflect.FileDescriptor

const file_server_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x13server/v1/api.proto\x12\x15messageloop.server.v1\"\xee\x02\n" +
	"\vPublication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12P\n" +
	"\vdestination\x18\x02 \x01(\v2..messageloop.server.v1.Publication.DestinationR\vdestination\x12D\n" +
	"\aoptions\x18\x03 \x01(\v2*.messageloop.server.v1.Publication.OptionsR\aoptions\x12!\n" +
	"\fpayload_blob\x18\x04 \x01(\fR\vpayloadBlob\x12!\n" +
	"\fpayload_text\x18\x05 \x01(\tR\vpayloadText\x1a*\n" +
	"\aOptions\x12\x1f\n" +
	"\vadd_history\x18\x01 \x01(\bR\n" +
	"addHistory\x1aE\n" +
	"\vDestination\x12\x1a\n" +
	"\bsessions\x18\x01 \x03(\tR\bsessions\x12\x1a\n" +
	"\bchannels\x18\x02 \x03(\tR\bchannels\"\x85\x02\n" +
	"\x0ePublishRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12O\n" +
	"\bmetadata\x18\x02 \x03(\v23.messageloop.server.v1.PublishRequest.MetadataEntryR\bmetadata\x12F\n" +
	"\fpublications\x18\x03 \x03(\v2\".messageloop.server.v1.PublicationR\fpublications\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0e\n" +
	"\fPublishReply\"\x13\n" +
	"\x11DisconnectRequest\"\x11\n" +
	"\x0fDisconnectReply\"\x12\n" +
	"\x10SubscribeRequest\"\x10\n" +
	"\x0eSubscribeReply\"\x14\n" +
	"\x12UnsubscribeRequest\"\x12\n" +
	"\x10UnsubscribeReply2\x81\x03\n" +
	"\n" +
	"APIService\x12U\n" +
	"\aPublish\x12%.messageloop.server.v1.PublishRequest\x1a#.messageloop.server.v1.PublishReply\x12^\n" +
	"\n" +
	"Disconnect\x12(.messageloop.server.v1.DisconnectRequest\x1a&.messageloop.server.v1.DisconnectReply\x12[\n" +
	"\tSubscribe\x12'.messageloop.server.v1.SubscribeRequest\x1a%.messageloop.server.v1.SubscribeReply\x12_\n" +
	"\vUnsubscribe\x12'.messageloop.server.v1.SubscribeRequest\x1a'.messageloop.server.v1.UnsubscribeReplyBDZBgithub.com/deeplooplabs/messageloop/genproto/go/server/v1;serverpbb\x06proto3"

var (
	file_server_v1_api_proto_rawDescOnce sync.Once
	file_server_v1_api_proto_rawDescData []byte
)

func file_server_v1_api_proto_rawDescGZIP() []byte {
	file_server_v1_api_proto_rawDescOnce.Do(func() {
		file_server_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_v1_api_proto_rawDesc), len(file_server_v1_api_proto_rawDesc)))
	})
	return file_server_v1_api_proto_rawDescData
}

var file_server_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_server_v1_api_proto_goTypes = []any{
	(*Publication)(nil),             // 0: messageloop.server.v1.Publication
	(*PublishRequest)(nil),          // 1: messageloop.server.v1.PublishRequest
	(*PublishReply)(nil),            // 2: messageloop.server.v1.PublishReply
	(*DisconnectRequest)(nil),       // 3: messageloop.server.v1.DisconnectRequest
	(*DisconnectReply)(nil),         // 4: messageloop.server.v1.DisconnectReply
	(*SubscribeRequest)(nil),        // 5: messageloop.server.v1.SubscribeRequest
	(*SubscribeReply)(nil),          // 6: messageloop.server.v1.SubscribeReply
	(*UnsubscribeRequest)(nil),      // 7: messageloop.server.v1.UnsubscribeRequest
	(*UnsubscribeReply)(nil),        // 8: messageloop.server.v1.UnsubscribeReply
	(*Publication_Options)(nil),     // 9: messageloop.server.v1.Publication.Options
	(*Publication_Destination)(nil), // 10: messageloop.server.v1.Publication.Destination
	nil,                             // 11: messageloop.server.v1.PublishRequest.MetadataEntry
}
var file_server_v1_api_proto_depIdxs = []int32{
	10, // 0: messageloop.server.v1.Publication.destination:type_name -> messageloop.server.v1.Publication.Destination
	9,  // 1: messageloop.server.v1.Publication.options:type_name -> messageloop.server.v1.Publication.Options
	11, // 2: messageloop.server.v1.PublishRequest.metadata:type_name -> messageloop.server.v1.PublishRequest.MetadataEntry
	0,  // 3: messageloop.server.v1.PublishRequest.publications:type_name -> messageloop.server.v1.Publication
	1,  // 4: messageloop.server.v1.APIService.Publish:input_type -> messageloop.server.v1.PublishRequest
	3,  // 5: messageloop.server.v1.APIService.Disconnect:input_type -> messageloop.server.v1.DisconnectRequest
	5,  // 6: messageloop.server.v1.APIService.Subscribe:input_type -> messageloop.server.v1.SubscribeRequest
	5,  // 7: messageloop.server.v1.APIService.Unsubscribe:input_type -> messageloop.server.v1.SubscribeRequest
	2,  // 8: messageloop.server.v1.APIService.Publish:output_type -> messageloop.server.v1.PublishReply
	4,  // 9: messageloop.server.v1.APIService.Disconnect:output_type -> messageloop.server.v1.DisconnectReply
	6,  // 10: messageloop.server.v1.APIService.Subscribe:output_type -> messageloop.server.v1.SubscribeReply
	8,  // 11: messageloop.server.v1.APIService.Unsubscribe:output_type -> messageloop.server.v1.UnsubscribeReply
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_server_v1_api_proto_init() }
func file_server_v1_api_proto_init() {
	if File_server_v1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_v1_api_proto_rawDesc), len(file_server_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_v1_api_proto_goTypes,
		DependencyIndexes: file_server_v1_api_proto_depIdxs,
		MessageInfos:      file_server_v1_api_proto_msgTypes,
	}.Build()
	File_server_v1_api_proto = out.File
	file_server_v1_api_proto_goTypes = nil
	file_server_v1_api_proto_depIdxs = nil
}
