// @generated by protoc-gen-es v2.10.0 with parameter "target=ts,import_extension=none"
// @generated from file server/v1/api.proto (package messageloop.server.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file server/v1/api.proto.
 */
export const file_server_v1_api: GenFile = /*@__PURE__*/
  fileDesc("ChNzZXJ2ZXIvdjEvYXBpLnByb3RvEhVtZXNzYWdlbG9vcC5zZXJ2ZXIudjEimgIKC1B1YmxpY2F0aW9uEgoKAmlkGAEgASgJEkMKC2Rlc3RpbmF0aW9uGAIgASgLMi4ubWVzc2FnZWxvb3Auc2VydmVyLnYxLlB1YmxpY2F0aW9uLkRlc3RpbmF0aW9uEjsKB29wdGlvbnMYAyABKAsyKi5tZXNzYWdlbG9vcC5zZXJ2ZXIudjEuUHVibGljYXRpb24uT3B0aW9ucxIUCgxwYXlsb2FkX2Jsb2IYBCABKAwSFAoMcGF5bG9hZF90ZXh0GAUgASgJGh4KB09wdGlvbnMSEwoLYWRkX2hpc3RvcnkYASABKAgaMQoLRGVzdGluYXRpb24SEAoIc2Vzc2lvbnMYASADKAkSEAoIY2hhbm5lbHMYAiADKAki1gEKDlB1Ymxpc2hSZXF1ZXN0EhIKCnJlcXVlc3RfaWQYASABKAkSRQoIbWV0YWRhdGEYAiADKAsyMy5tZXNzYWdlbG9vcC5zZXJ2ZXIudjEuUHVibGlzaFJlcXVlc3QuTWV0YWRhdGFFbnRyeRI4CgxwdWJsaWNhdGlvbnMYAyADKAsyIi5tZXNzYWdlbG9vcC5zZXJ2ZXIudjEuUHVibGljYXRpb24aLwoNTWV0YWRhdGFFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIg4KDFB1Ymxpc2hSZXBseSITChFEaXNjb25uZWN0UmVxdWVzdCIRCg9EaXNjb25uZWN0UmVwbHkiEgoQU3Vic2NyaWJlUmVxdWVzdCIQCg5TdWJzY3JpYmVSZXBseSIUChJVbnN1YnNjcmliZVJlcXVlc3QiEgoQVW5zdWJzY3JpYmVSZXBseTKBAwoKQVBJU2VydmljZRJVCgdQdWJsaXNoEiUubWVzc2FnZWxvb3Auc2VydmVyLnYxLlB1Ymxpc2hSZXF1ZXN0GiMubWVzc2FnZWxvb3Auc2VydmVyLnYxLlB1Ymxpc2hSZXBseRJeCgpEaXNjb25uZWN0EigubWVzc2FnZWxvb3Auc2VydmVyLnYxLkRpc2Nvbm5lY3RSZXF1ZXN0GiYubWVzc2FnZWxvb3Auc2VydmVyLnYxLkRpc2Nvbm5lY3RSZXBseRJbCglTdWJzY3JpYmUSJy5tZXNzYWdlbG9vcC5zZXJ2ZXIudjEuU3Vic2NyaWJlUmVxdWVzdBolLm1lc3NhZ2Vsb29wLnNlcnZlci52MS5TdWJzY3JpYmVSZXBseRJfCgtVbnN1YnNjcmliZRInLm1lc3NhZ2Vsb29wLnNlcnZlci52MS5TdWJzY3JpYmVSZXF1ZXN0GicubWVzc2FnZWxvb3Auc2VydmVyLnYxLlVuc3Vic2NyaWJlUmVwbHlCRFpCZ2l0aHViLmNvbS9kZWVwbG9vcGxhYnMvbWVzc2FnZWxvb3AvZ2VucHJvdG8vZ28vc2VydmVyL3YxO3NlcnZlcnBiYgZwcm90bzM");

/**
 * @generated from message messageloop.server.v1.Publication
 */
export type Publication = Message<"messageloop.server.v1.Publication"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: messageloop.server.v1.Publication.Destination destination = 2;
   */
  destination?: Publication_Destination;

  /**
   * @generated from field: messageloop.server.v1.Publication.Options options = 3;
   */
  options?: Publication_Options;

  /**
   * @generated from field: bytes payload_blob = 4;
   */
  payloadBlob: Uint8Array;

  /**
   * @generated from field: string payload_text = 5;
   */
  payloadText: string;
};

/**
 * Describes the message messageloop.server.v1.Publication.
 * Use `create(PublicationSchema)` to create a new message.
 */
export const PublicationSchema: GenMessage<Publication> = /*@__PURE__*/
  messageDesc(file_server_v1_api, 0);

/**
 * @generated from message messageloop.server.v1.Publication.Options
 */
export type Publication_Options = Message<"messageloop.server.v1.Publication.Options"> & {
  /**
   * @generated from field: bool add_history = 1;
   */
  addHistory: boolean;
};

/**
 * Describes the message messageloop.server.v1.Publication.Options.
 * Use `create(Publication_OptionsSchema)` to create a new message.
 */
export const Publication_OptionsSchema: GenMessage<Publication_Options> = /*@__PURE__*/
  messageDesc(file_server_v1_api, 0, 0);

/**
 * @generated from message messageloop.server.v1.Publication.Destination
 */
export type Publication_Destination = Message<"messageloop.server.v1.Publication.Destination"> & {
  /**
   * @generated from field: repeated string sessions = 1;
   */
  sessions: string[];

  /**
   * @generated from field: repeated string channels = 2;
   */
  channels: string[];
};

/**
 * Describes the message messageloop.server.v1.Publication.Destination.
 * Use `create(Publication_DestinationSchema)` to create a new message.
 */
export const Publication_DestinationSchema: GenMessage<Publication_Destination> = /*@__PURE__*/
  messageDesc(file_server_v1_api, 0, 1);

/**
 * @generated from message messageloop.server.v1.PublishRequest
 */
export type PublishRequest = Message<"messageloop.server.v1.PublishRequest"> & {
  /**
   * @generated from field: string request_id = 1;
   */
  requestId: string;

  /**
   * @generated from field: map<string, string> metadata = 2;
   */
  metadata: { [key: string]: string };

  /**
   * @generated from field: repeated messageloop.server.v1.Publication publications = 3;
   */
  publications: Publication[];
};

/**
 * Describes the message messageloop.server.v1.PublishRequest.
 * Use `create(PublishRequestSchema)` to create a new message.
 */
export const PublishRequestSchema: GenMessage<PublishRequest> = /*@__PURE__*/
  messageDesc(file_server_v1_api, 1);

/**
 * @generated from message messageloop.server.v1.PublishReply
 */
export type PublishReply = Message<"messageloop.server.v1.PublishReply"> & {
};

/**
 * Describes the message messageloop.server.v1.PublishReply.
 * Use `create(PublishReplySchema)` to create a new message.
 */
export const PublishReplySchema: GenMessage<PublishReply> = /*@__PURE__*/
  messageDesc(file_server_v1_api, 2);

/**
 * @generated from message messageloop.server.v1.DisconnectRequest
 */
export type DisconnectRequest = Message<"messageloop.server.v1.DisconnectRequest"> & {
};

/**
 * Describes the message messageloop.server.v1.DisconnectRequest.
 * Use `create(DisconnectRequestSchema)` to create a new message.
 */
export const DisconnectRequestSchema: GenMessage<DisconnectRequest> = /*@__PURE__*/
  messageDesc(file_server_v1_api, 3);

/**
 * @generated from message messageloop.server.v1.DisconnectReply
 */
export type DisconnectReply = Message<"messageloop.server.v1.DisconnectReply"> & {
};

/**
 * Describes the message messageloop.server.v1.DisconnectReply.
 * Use `create(DisconnectReplySchema)` to create a new message.
 */
export const DisconnectReplySchema: GenMessage<DisconnectReply> = /*@__PURE__*/
  messageDesc(file_server_v1_api, 4);

/**
 * @generated from message messageloop.server.v1.SubscribeRequest
 */
export type SubscribeRequest = Message<"messageloop.server.v1.SubscribeRequest"> & {
};

/**
 * Describes the message messageloop.server.v1.SubscribeRequest.
 * Use `create(SubscribeRequestSchema)` to create a new message.
 */
export const SubscribeRequestSchema: GenMessage<SubscribeRequest> = /*@__PURE__*/
  messageDesc(file_server_v1_api, 5);

/**
 * @generated from message messageloop.server.v1.SubscribeReply
 */
export type SubscribeReply = Message<"messageloop.server.v1.SubscribeReply"> & {
};

/**
 * Describes the message messageloop.server.v1.SubscribeReply.
 * Use `create(SubscribeReplySchema)` to create a new message.
 */
export const SubscribeReplySchema: GenMessage<SubscribeReply> = /*@__PURE__*/
  messageDesc(file_server_v1_api, 6);

/**
 * @generated from message messageloop.server.v1.UnsubscribeRequest
 */
export type UnsubscribeRequest = Message<"messageloop.server.v1.UnsubscribeRequest"> & {
};

/**
 * Describes the message messageloop.server.v1.UnsubscribeRequest.
 * Use `create(UnsubscribeRequestSchema)` to create a new message.
 */
export const UnsubscribeRequestSchema: GenMessage<UnsubscribeRequest> = /*@__PURE__*/
  messageDesc(file_server_v1_api, 7);

/**
 * @generated from message messageloop.server.v1.UnsubscribeReply
 */
export type UnsubscribeReply = Message<"messageloop.server.v1.UnsubscribeReply"> & {
};

/**
 * Describes the message messageloop.server.v1.UnsubscribeReply.
 * Use `create(UnsubscribeReplySchema)` to create a new message.
 */
export const UnsubscribeReplySchema: GenMessage<UnsubscribeReply> = /*@__PURE__*/
  messageDesc(file_server_v1_api, 8);

/**
 * @generated from service messageloop.server.v1.APIService
 */
export const APIService: GenService<{
  /**
   * @generated from rpc messageloop.server.v1.APIService.Publish
   */
  publish: {
    methodKind: "unary";
    input: typeof PublishRequestSchema;
    output: typeof PublishReplySchema;
  },
  /**
   * @generated from rpc messageloop.server.v1.APIService.Disconnect
   */
  disconnect: {
    methodKind: "unary";
    input: typeof DisconnectRequestSchema;
    output: typeof DisconnectReplySchema;
  },
  /**
   * @generated from rpc messageloop.server.v1.APIService.Subscribe
   */
  subscribe: {
    methodKind: "unary";
    input: typeof SubscribeRequestSchema;
    output: typeof SubscribeReplySchema;
  },
  /**
   * @generated from rpc messageloop.server.v1.APIService.Unsubscribe
   */
  unsubscribe: {
    methodKind: "unary";
    input: typeof SubscribeRequestSchema;
    output: typeof UnsubscribeReplySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_server_v1_api, 0);

