// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/service.proto

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

package clientpb

import (
	pb "github.com/cloudevents/sdk-go/binding/format/protobuf/v2/pb"
	v1 "github.com/fleetlit/messageloop/genproto/shared/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InboundMessage struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Channel  string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Method   string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Metadata map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Time     uint64                 `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	// Types that are valid to be assigned to Envelope:
	//
	//	*InboundMessage_Connect
	//	*InboundMessage_Subscribe
	//	*InboundMessage_Unsubscribe
	//	*InboundMessage_RpcRequest
	//	*InboundMessage_Ping
	//	*InboundMessage_Publish
	//	*InboundMessage_SubRefresh
	Envelope      isInboundMessage_Envelope `protobuf_oneof:"envelope"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundMessage) Reset() {
	*x = InboundMessage{}
	mi := &file_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundMessage) ProtoMessage() {}

func (x *InboundMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundMessage.ProtoReflect.Descriptor instead.
func (*InboundMessage) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *InboundMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InboundMessage) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *InboundMessage) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InboundMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InboundMessage) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *InboundMessage) GetEnvelope() isInboundMessage_Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *InboundMessage) GetConnect() *Connect {
	if x != nil {
		if x, ok := x.Envelope.(*InboundMessage_Connect); ok {
			return x.Connect
		}
	}
	return nil
}

func (x *InboundMessage) GetSubscribe() *Subscribe {
	if x != nil {
		if x, ok := x.Envelope.(*InboundMessage_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *InboundMessage) GetUnsubscribe() *Unsubscribe {
	if x != nil {
		if x, ok := x.Envelope.(*InboundMessage_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

func (x *InboundMessage) GetRpcRequest() *pb.CloudEvent {
	if x != nil {
		if x, ok := x.Envelope.(*InboundMessage_RpcRequest); ok {
			return x.RpcRequest
		}
	}
	return nil
}

func (x *InboundMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Envelope.(*InboundMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *InboundMessage) GetPublish() *pb.CloudEvent {
	if x != nil {
		if x, ok := x.Envelope.(*InboundMessage_Publish); ok {
			return x.Publish
		}
	}
	return nil
}

func (x *InboundMessage) GetSubRefresh() *SubRefresh {
	if x != nil {
		if x, ok := x.Envelope.(*InboundMessage_SubRefresh); ok {
			return x.SubRefresh
		}
	}
	return nil
}

type isInboundMessage_Envelope interface {
	isInboundMessage_Envelope()
}

type InboundMessage_Connect struct {
	Connect *Connect `protobuf:"bytes,11,opt,name=connect,proto3,oneof"`
}

type InboundMessage_Subscribe struct {
	Subscribe *Subscribe `protobuf:"bytes,12,opt,name=subscribe,proto3,oneof"`
}

type InboundMessage_Unsubscribe struct {
	Unsubscribe *Unsubscribe `protobuf:"bytes,13,opt,name=unsubscribe,proto3,oneof"`
}

type InboundMessage_RpcRequest struct {
	RpcRequest *pb.CloudEvent `protobuf:"bytes,14,opt,name=rpc_request,proto3,oneof"`
}

type InboundMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,15,opt,name=ping,proto3,oneof"`
}

type InboundMessage_Publish struct {
	Publish *pb.CloudEvent `protobuf:"bytes,16,opt,name=publish,proto3,oneof"`
}

type InboundMessage_SubRefresh struct {
	SubRefresh *SubRefresh `protobuf:"bytes,17,opt,name=sub_refresh,proto3,oneof"`
}

func (*InboundMessage_Connect) isInboundMessage_Envelope() {}

func (*InboundMessage_Subscribe) isInboundMessage_Envelope() {}

func (*InboundMessage_Unsubscribe) isInboundMessage_Envelope() {}

func (*InboundMessage_RpcRequest) isInboundMessage_Envelope() {}

func (*InboundMessage_Ping) isInboundMessage_Envelope() {}

func (*InboundMessage_Publish) isInboundMessage_Envelope() {}

func (*InboundMessage_SubRefresh) isInboundMessage_Envelope() {}

type OutboundMessage struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Time     uint64                 `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	// Types that are valid to be assigned to Envelope:
	//
	//	*OutboundMessage_Error
	//	*OutboundMessage_Connected
	//	*OutboundMessage_SubscribeAck
	//	*OutboundMessage_UnsubscribeAck
	//	*OutboundMessage_RpcReply
	//	*OutboundMessage_Pong
	//	*OutboundMessage_PublishAck
	//	*OutboundMessage_Publication
	//	*OutboundMessage_SubRefreshAck
	Envelope      isOutboundMessage_Envelope `protobuf_oneof:"envelope"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundMessage) Reset() {
	*x = OutboundMessage{}
	mi := &file_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundMessage) ProtoMessage() {}

func (x *OutboundMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundMessage.ProtoReflect.Descriptor instead.
func (*OutboundMessage) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *OutboundMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OutboundMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *OutboundMessage) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *OutboundMessage) GetEnvelope() isOutboundMessage_Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *OutboundMessage) GetError() *v1.Error {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *OutboundMessage) GetConnected() *Connected {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_Connected); ok {
			return x.Connected
		}
	}
	return nil
}

func (x *OutboundMessage) GetSubscribeAck() *SubscribeAck {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_SubscribeAck); ok {
			return x.SubscribeAck
		}
	}
	return nil
}

func (x *OutboundMessage) GetUnsubscribeAck() *UnsubscribeAck {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_UnsubscribeAck); ok {
			return x.UnsubscribeAck
		}
	}
	return nil
}

func (x *OutboundMessage) GetRpcReply() *pb.CloudEvent {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_RpcReply); ok {
			return x.RpcReply
		}
	}
	return nil
}

func (x *OutboundMessage) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *OutboundMessage) GetPublishAck() *PublishAck {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_PublishAck); ok {
			return x.PublishAck
		}
	}
	return nil
}

func (x *OutboundMessage) GetPublication() *Publication {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_Publication); ok {
			return x.Publication
		}
	}
	return nil
}

func (x *OutboundMessage) GetSubRefreshAck() *SubRefreshAck {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_SubRefreshAck); ok {
			return x.SubRefreshAck
		}
	}
	return nil
}

type isOutboundMessage_Envelope interface {
	isOutboundMessage_Envelope()
}

type OutboundMessage_Error struct {
	Error *v1.Error `protobuf:"bytes,11,opt,name=error,proto3,oneof"`
}

type OutboundMessage_Connected struct {
	Connected *Connected `protobuf:"bytes,12,opt,name=connected,proto3,oneof"`
}

type OutboundMessage_SubscribeAck struct {
	SubscribeAck *SubscribeAck `protobuf:"bytes,13,opt,name=subscribe_ack,proto3,oneof"`
}

type OutboundMessage_UnsubscribeAck struct {
	UnsubscribeAck *UnsubscribeAck `protobuf:"bytes,14,opt,name=unsubscribe_ack,proto3,oneof"`
}

type OutboundMessage_RpcReply struct {
	RpcReply *pb.CloudEvent `protobuf:"bytes,15,opt,name=rpc_reply,proto3,oneof"`
}

type OutboundMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,16,opt,name=pong,proto3,oneof"`
}

type OutboundMessage_PublishAck struct {
	PublishAck *PublishAck `protobuf:"bytes,17,opt,name=publish_ack,proto3,oneof"`
}

type OutboundMessage_Publication struct {
	Publication *Publication `protobuf:"bytes,18,opt,name=publication,proto3,oneof"`
}

type OutboundMessage_SubRefreshAck struct {
	SubRefreshAck *SubRefreshAck `protobuf:"bytes,19,opt,name=sub_refresh_ack,proto3,oneof"`
}

func (*OutboundMessage_Error) isOutboundMessage_Envelope() {}

func (*OutboundMessage_Connected) isOutboundMessage_Envelope() {}

func (*OutboundMessage_SubscribeAck) isOutboundMessage_Envelope() {}

func (*OutboundMessage_UnsubscribeAck) isOutboundMessage_Envelope() {}

func (*OutboundMessage_RpcReply) isOutboundMessage_Envelope() {}

func (*OutboundMessage_Pong) isOutboundMessage_Envelope() {}

func (*OutboundMessage_PublishAck) isOutboundMessage_Envelope() {}

func (*OutboundMessage_Publication) isOutboundMessage_Envelope() {}

func (*OutboundMessage_SubRefreshAck) isOutboundMessage_Envelope() {}

type Connect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,proto3" json:"client_id,omitempty"`
	ClientType    string                 `protobuf:"bytes,2,opt,name=client_type,proto3" json:"client_type,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Subscriptions []*Subscription        `protobuf:"bytes,5,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connect) Reset() {
	*x = Connect{}
	mi := &file_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connect) ProtoMessage() {}

func (x *Connect) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connect.ProtoReflect.Descriptor instead.
func (*Connect) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *Connect) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Connect) GetClientType() string {
	if x != nil {
		return x.ClientType
	}
	return ""
}

func (x *Connect) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Connect) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Connect) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type RPCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Payload       *pb.CloudEvent         `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCRequest) Reset() {
	*x = RPCRequest{}
	mi := &file_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCRequest) ProtoMessage() {}

func (x *RPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCRequest.ProtoReflect.Descriptor instead.
func (*RPCRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *RPCRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *RPCRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RPCRequest) GetPayload() *pb.CloudEvent {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RPCReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *v1.Error              `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Payload       *pb.CloudEvent         `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCReply) Reset() {
	*x = RPCReply{}
	mi := &file_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCReply) ProtoMessage() {}

func (x *RPCReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCReply.ProtoReflect.Descriptor instead.
func (*RPCReply) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *RPCReply) GetError() *v1.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *RPCReply) GetPayload() *pb.CloudEvent {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Payload       *pb.CloudEvent         `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Message) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Message) GetPayload() *pb.CloudEvent {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Publication struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelopes     []*Message             `protobuf:"bytes,3,rep,name=envelopes,proto3" json:"envelopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Publication) Reset() {
	*x = Publication{}
	mi := &file_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Publication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publication) ProtoMessage() {}

func (x *Publication) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publication.ProtoReflect.Descriptor instead.
func (*Publication) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *Publication) GetEnvelopes() []*Message {
	if x != nil {
		return x.Envelopes
	}
	return nil
}

type Connected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,proto3" json:"session_id,omitempty"`
	Subscriptions []*Subscription        `protobuf:"bytes,2,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Publications  []*Publication         `protobuf:"bytes,3,rep,name=publications,proto3" json:"publications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connected) Reset() {
	*x = Connected{}
	mi := &file_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connected) ProtoMessage() {}

func (x *Connected) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connected.ProtoReflect.Descriptor instead.
func (*Connected) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *Connected) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Connected) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *Connected) GetPublications() []*Publication {
	if x != nil {
		return x.Publications
	}
	return nil
}

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Ephemeral     bool                   `protobuf:"varint,2,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *Subscription) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Subscription) GetEphemeral() bool {
	if x != nil {
		return x.Ephemeral
	}
	return false
}

func (x *Subscription) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Subscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *Subscribe) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type SubscribeAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeAck) Reset() {
	*x = SubscribeAck{}
	mi := &file_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeAck) ProtoMessage() {}

func (x *SubscribeAck) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeAck.ProtoReflect.Descriptor instead.
func (*SubscribeAck) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *SubscribeAck) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type Unsubscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unsubscribe) Reset() {
	*x = Unsubscribe{}
	mi := &file_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unsubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unsubscribe) ProtoMessage() {}

func (x *Unsubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unsubscribe.ProtoReflect.Descriptor instead.
func (*Unsubscribe) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *Unsubscribe) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type UnsubscribeAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeAck) Reset() {
	*x = UnsubscribeAck{}
	mi := &file_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeAck) ProtoMessage() {}

func (x *UnsubscribeAck) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeAck.ProtoReflect.Descriptor instead.
func (*UnsubscribeAck) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *UnsubscribeAck) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type RefreshSub struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshSub) Reset() {
	*x = RefreshSub{}
	mi := &file_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSub) ProtoMessage() {}

func (x *RefreshSub) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSub.ProtoReflect.Descriptor instead.
func (*RefreshSub) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *RefreshSub) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{14}
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{15}
}

type PublishAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishAck) Reset() {
	*x = PublishAck{}
	mi := &file_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishAck) ProtoMessage() {}

func (x *PublishAck) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishAck.ProtoReflect.Descriptor instead.
func (*PublishAck) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{16}
}

func (x *PublishAck) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SubRefresh struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []string               `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubRefresh) Reset() {
	*x = SubRefresh{}
	mi := &file_v1_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubRefresh) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubRefresh) ProtoMessage() {}

func (x *SubRefresh) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubRefresh.ProtoReflect.Descriptor instead.
func (*SubRefresh) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{17}
}

func (x *SubRefresh) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

type SubRefreshAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubRefreshAck) Reset() {
	*x = SubRefreshAck{}
	mi := &file_v1_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubRefreshAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubRefreshAck) ProtoMessage() {}

func (x *SubRefreshAck) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubRefreshAck.ProtoReflect.Descriptor instead.
func (*SubRefreshAck) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{18}
}

var File_v1_service_proto protoreflect.FileDescriptor

const file_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x10v1/service.proto\x12\x0emessageloop.v1\x1a\x16shared/v1/errors.proto\x1a&includes/cloudevents/cloudevents.proto\"\x94\x05\n" +
	"\x0eInboundMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12H\n" +
	"\bmetadata\x18\x04 \x03(\v2,.messageloop.v1.InboundMessage.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x04R\x04time\x123\n" +
	"\aconnect\x18\v \x01(\v2\x17.messageloop.v1.ConnectH\x00R\aconnect\x129\n" +
	"\tsubscribe\x18\f \x01(\v2\x19.messageloop.v1.SubscribeH\x00R\tsubscribe\x12?\n" +
	"\vunsubscribe\x18\r \x01(\v2\x1b.messageloop.v1.UnsubscribeH\x00R\vunsubscribe\x12A\n" +
	"\vrpc_request\x18\x0e \x01(\v2\x1d.io.cloudevents.v1.CloudEventH\x00R\vrpc_request\x12*\n" +
	"\x04ping\x18\x0f \x01(\v2\x14.messageloop.v1.PingH\x00R\x04ping\x129\n" +
	"\apublish\x18\x10 \x01(\v2\x1d.io.cloudevents.v1.CloudEventH\x00R\apublish\x12>\n" +
	"\vsub_refresh\x18\x11 \x01(\v2\x1a.messageloop.v1.SubRefreshH\x00R\vsub_refresh\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\benvelope\"\x83\x06\n" +
	"\x0fOutboundMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12I\n" +
	"\bmetadata\x18\x02 \x03(\v2-.messageloop.v1.OutboundMessage.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04time\x18\x03 \x01(\x04R\x04time\x124\n" +
	"\x05error\x18\v \x01(\v2\x1c.messageloop.shared.v1.ErrorH\x00R\x05error\x129\n" +
	"\tconnected\x18\f \x01(\v2\x19.messageloop.v1.ConnectedH\x00R\tconnected\x12D\n" +
	"\rsubscribe_ack\x18\r \x01(\v2\x1c.messageloop.v1.SubscribeAckH\x00R\rsubscribe_ack\x12J\n" +
	"\x0funsubscribe_ack\x18\x0e \x01(\v2\x1e.messageloop.v1.UnsubscribeAckH\x00R\x0funsubscribe_ack\x12=\n" +
	"\trpc_reply\x18\x0f \x01(\v2\x1d.io.cloudevents.v1.CloudEventH\x00R\trpc_reply\x12*\n" +
	"\x04pong\x18\x10 \x01(\v2\x14.messageloop.v1.PongH\x00R\x04pong\x12>\n" +
	"\vpublish_ack\x18\x11 \x01(\v2\x1a.messageloop.v1.PublishAckH\x00R\vpublish_ack\x12?\n" +
	"\vpublication\x18\x12 \x01(\v2\x1b.messageloop.v1.PublicationH\x00R\vpublication\x12I\n" +
	"\x0fsub_refresh_ack\x18\x13 \x01(\v2\x1d.messageloop.v1.SubRefreshAckH\x00R\x0fsub_refresh_ack\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\benvelope\"\xbd\x01\n" +
	"\aConnect\x12\x1c\n" +
	"\tclient_id\x18\x01 \x01(\tR\tclient_id\x12 \n" +
	"\vclient_type\x18\x02 \x01(\tR\vclient_type\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12B\n" +
	"\rsubscriptions\x18\x05 \x03(\v2\x1c.messageloop.v1.SubscriptionR\rsubscriptions\"w\n" +
	"\n" +
	"RPCRequest\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x127\n" +
	"\apayload\x18\x03 \x01(\v2\x1d.io.cloudevents.v1.CloudEventR\apayload\"w\n" +
	"\bRPCReply\x122\n" +
	"\x05error\x18\x01 \x01(\v2\x1c.messageloop.shared.v1.ErrorR\x05error\x127\n" +
	"\apayload\x18\x03 \x01(\v2\x1d.io.cloudevents.v1.CloudEventR\apayload\"\x84\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x127\n" +
	"\apayload\x18\x04 \x01(\v2\x1d.io.cloudevents.v1.CloudEventR\apayload\"D\n" +
	"\vPublication\x125\n" +
	"\tenvelopes\x18\x03 \x03(\v2\x17.messageloop.v1.MessageR\tenvelopes\"\xb0\x01\n" +
	"\tConnected\x12\x1e\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\n" +
	"session_id\x12B\n" +
	"\rsubscriptions\x18\x02 \x03(\v2\x1c.messageloop.v1.SubscriptionR\rsubscriptions\x12?\n" +
	"\fpublications\x18\x03 \x03(\v2\x1b.messageloop.v1.PublicationR\fpublications\"\\\n" +
	"\fSubscription\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x1c\n" +
	"\tephemeral\x18\x02 \x01(\bR\tephemeral\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"O\n" +
	"\tSubscribe\x12B\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x1c.messageloop.v1.SubscriptionR\rsubscriptions\"R\n" +
	"\fSubscribeAck\x12B\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x1c.messageloop.v1.SubscriptionR\rsubscriptions\"Q\n" +
	"\vUnsubscribe\x12B\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x1c.messageloop.v1.SubscriptionR\rsubscriptions\"T\n" +
	"\x0eUnsubscribeAck\x12B\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x1c.messageloop.v1.SubscriptionR\rsubscriptions\"P\n" +
	"\n" +
	"RefreshSub\x12B\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x1c.messageloop.v1.SubscriptionR\rsubscriptions\"\x06\n" +
	"\x04Ping\"\x06\n" +
	"\x04Pong\"$\n" +
	"\n" +
	"PublishAck\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\"(\n" +
	"\n" +
	"SubRefresh\x12\x1a\n" +
	"\bchannels\x18\x01 \x03(\tR\bchannels\"\x0f\n" +
	"\rSubRefreshAck2f\n" +
	"\x10MessagingService\x12R\n" +
	"\vMessageLoop\x12\x1e.messageloop.v1.InboundMessage\x1a\x1f.messageloop.v1.OutboundMessage(\x010\x01B@Z>github.com/fleetlit/messageloop/genproto/go/client/v1;clientpbb\x06proto3"

var (
	file_v1_service_proto_rawDescOnce sync.Once
	file_v1_service_proto_rawDescData []byte
)

func file_v1_service_proto_rawDescGZIP() []byte {
	file_v1_service_proto_rawDescOnce.Do(func() {
		file_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_service_proto_rawDesc), len(file_v1_service_proto_rawDesc)))
	})
	return file_v1_service_proto_rawDescData
}

var file_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_v1_service_proto_goTypes = []any{
	(*InboundMessage)(nil),  // 0: messageloop.v1.InboundMessage
	(*OutboundMessage)(nil), // 1: messageloop.v1.OutboundMessage
	(*Connect)(nil),         // 2: messageloop.v1.Connect
	(*RPCRequest)(nil),      // 3: messageloop.v1.RPCRequest
	(*RPCReply)(nil),        // 4: messageloop.v1.RPCReply
	(*Message)(nil),         // 5: messageloop.v1.Message
	(*Publication)(nil),     // 6: messageloop.v1.Publication
	(*Connected)(nil),       // 7: messageloop.v1.Connected
	(*Subscription)(nil),    // 8: messageloop.v1.Subscription
	(*Subscribe)(nil),       // 9: messageloop.v1.Subscribe
	(*SubscribeAck)(nil),    // 10: messageloop.v1.SubscribeAck
	(*Unsubscribe)(nil),     // 11: messageloop.v1.Unsubscribe
	(*UnsubscribeAck)(nil),  // 12: messageloop.v1.UnsubscribeAck
	(*RefreshSub)(nil),      // 13: messageloop.v1.RefreshSub
	(*Ping)(nil),            // 14: messageloop.v1.Ping
	(*Pong)(nil),            // 15: messageloop.v1.Pong
	(*PublishAck)(nil),      // 16: messageloop.v1.PublishAck
	(*SubRefresh)(nil),      // 17: messageloop.v1.SubRefresh
	(*SubRefreshAck)(nil),   // 18: messageloop.v1.SubRefreshAck
	nil,                     // 19: messageloop.v1.InboundMessage.MetadataEntry
	nil,                     // 20: messageloop.v1.OutboundMessage.MetadataEntry
	(*pb.CloudEvent)(nil),   // 21: io.cloudevents.v1.CloudEvent
	(*v1.Error)(nil),        // 22: messageloop.shared.v1.Error
}
var file_v1_service_proto_depIdxs = []int32{
	19, // 0: messageloop.v1.InboundMessage.metadata:type_name -> messageloop.v1.InboundMessage.MetadataEntry
	2,  // 1: messageloop.v1.InboundMessage.connect:type_name -> messageloop.v1.Connect
	9,  // 2: messageloop.v1.InboundMessage.subscribe:type_name -> messageloop.v1.Subscribe
	11, // 3: messageloop.v1.InboundMessage.unsubscribe:type_name -> messageloop.v1.Unsubscribe
	21, // 4: messageloop.v1.InboundMessage.rpc_request:type_name -> io.cloudevents.v1.CloudEvent
	14, // 5: messageloop.v1.InboundMessage.ping:type_name -> messageloop.v1.Ping
	21, // 6: messageloop.v1.InboundMessage.publish:type_name -> io.cloudevents.v1.CloudEvent
	17, // 7: messageloop.v1.InboundMessage.sub_refresh:type_name -> messageloop.v1.SubRefresh
	20, // 8: messageloop.v1.OutboundMessage.metadata:type_name -> messageloop.v1.OutboundMessage.MetadataEntry
	22, // 9: messageloop.v1.OutboundMessage.error:type_name -> messageloop.shared.v1.Error
	7,  // 10: messageloop.v1.OutboundMessage.connected:type_name -> messageloop.v1.Connected
	10, // 11: messageloop.v1.OutboundMessage.subscribe_ack:type_name -> messageloop.v1.SubscribeAck
	12, // 12: messageloop.v1.OutboundMessage.unsubscribe_ack:type_name -> messageloop.v1.UnsubscribeAck
	21, // 13: messageloop.v1.OutboundMessage.rpc_reply:type_name -> io.cloudevents.v1.CloudEvent
	15, // 14: messageloop.v1.OutboundMessage.pong:type_name -> messageloop.v1.Pong
	16, // 15: messageloop.v1.OutboundMessage.publish_ack:type_name -> messageloop.v1.PublishAck
	6,  // 16: messageloop.v1.OutboundMessage.publication:type_name -> messageloop.v1.Publication
	18, // 17: messageloop.v1.OutboundMessage.sub_refresh_ack:type_name -> messageloop.v1.SubRefreshAck
	8,  // 18: messageloop.v1.Connect.subscriptions:type_name -> messageloop.v1.Subscription
	21, // 19: messageloop.v1.RPCRequest.payload:type_name -> io.cloudevents.v1.CloudEvent
	22, // 20: messageloop.v1.RPCReply.error:type_name -> messageloop.shared.v1.Error
	21, // 21: messageloop.v1.RPCReply.payload:type_name -> io.cloudevents.v1.CloudEvent
	21, // 22: messageloop.v1.Message.payload:type_name -> io.cloudevents.v1.CloudEvent
	5,  // 23: messageloop.v1.Publication.envelopes:type_name -> messageloop.v1.Message
	8,  // 24: messageloop.v1.Connected.subscriptions:type_name -> messageloop.v1.Subscription
	6,  // 25: messageloop.v1.Connected.publications:type_name -> messageloop.v1.Publication
	8,  // 26: messageloop.v1.Subscribe.subscriptions:type_name -> messageloop.v1.Subscription
	8,  // 27: messageloop.v1.SubscribeAck.subscriptions:type_name -> messageloop.v1.Subscription
	8,  // 28: messageloop.v1.Unsubscribe.subscriptions:type_name -> messageloop.v1.Subscription
	8,  // 29: messageloop.v1.UnsubscribeAck.subscriptions:type_name -> messageloop.v1.Subscription
	8,  // 30: messageloop.v1.RefreshSub.subscriptions:type_name -> messageloop.v1.Subscription
	0,  // 31: messageloop.v1.MessagingService.MessageLoop:input_type -> messageloop.v1.InboundMessage
	1,  // 32: messageloop.v1.MessagingService.MessageLoop:output_type -> messageloop.v1.OutboundMessage
	32, // [32:33] is the sub-list for method output_type
	31, // [31:32] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_v1_service_proto_init() }
func file_v1_service_proto_init() {
	if File_v1_service_proto != nil {
		return
	}
	file_v1_service_proto_msgTypes[0].OneofWrappers = []any{
		(*InboundMessage_Connect)(nil),
		(*InboundMessage_Subscribe)(nil),
		(*InboundMessage_Unsubscribe)(nil),
		(*InboundMessage_RpcRequest)(nil),
		(*InboundMessage_Ping)(nil),
		(*InboundMessage_Publish)(nil),
		(*InboundMessage_SubRefresh)(nil),
	}
	file_v1_service_proto_msgTypes[1].OneofWrappers = []any{
		(*OutboundMessage_Error)(nil),
		(*OutboundMessage_Connected)(nil),
		(*OutboundMessage_SubscribeAck)(nil),
		(*OutboundMessage_UnsubscribeAck)(nil),
		(*OutboundMessage_RpcReply)(nil),
		(*OutboundMessage_Pong)(nil),
		(*OutboundMessage_PublishAck)(nil),
		(*OutboundMessage_Publication)(nil),
		(*OutboundMessage_SubRefreshAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_service_proto_rawDesc), len(file_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_service_proto_goTypes,
		DependencyIndexes: file_v1_service_proto_depIdxs,
		MessageInfos:      file_v1_service_proto_msgTypes,
	}.Build()
	File_v1_service_proto = out.File
	file_v1_service_proto_goTypes = nil
	file_v1_service_proto_depIdxs = nil
}
