// @generated by protoc-gen-es v2.10.0 with parameter "target=ts,import_extension=none"
// @generated from file event/v1/events.proto (package messageloop.event.v1, syntax proto3)
/* eslint-disable */

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file event/v1/events.proto.
 */
export const file_event_v1_events: GenFile = /*@__PURE__*/
  fileDesc("ChVldmVudC92MS9ldmVudHMucHJvdG8SFG1lc3NhZ2Vsb29wLmV2ZW50LnYxIjUKDFB1Ymxpc2hFdmVudBIPCgdjaGFubmVsGAEgASgJEhQKDHBheWxvYWRfdGV4dBgCIAEoDEJKWkhnaXRodWIuY29tL21lc3NhZ2Vsb29waW8vbWVzc2FnZWxvb3Avc2hhcmVkL2dlbnByb3RvL2dvL2V2ZW50L3YxO2V2ZW50cGJiBnByb3RvMw");

/**
 * @generated from message messageloop.event.v1.PublishEvent
 */
export type PublishEvent = Message<"messageloop.event.v1.PublishEvent"> & {
  /**
   * @generated from field: string channel = 1;
   */
  channel: string;

  /**
   * @generated from field: bytes payload_text = 2;
   */
  payloadText: Uint8Array;
};

/**
 * Describes the message messageloop.event.v1.PublishEvent.
 * Use `create(PublishEventSchema)` to create a new message.
 */
export const PublishEventSchema: GenMessage<PublishEvent> = /*@__PURE__*/
  messageDesc(file_event_v1_events, 0);

