// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v2/common.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Encoding 定义编码类型
type Encoding int32

const (
	Encoding_ENCODING_UNSPECIFIED Encoding = 0
	Encoding_ENCODING_JSON        Encoding = 1
	Encoding_ENCODING_PROTOBUF    Encoding = 2
	Encoding_ENCODING_MSGPACK     Encoding = 3 // 扩展预留
	Encoding_ENCODING_CBOR        Encoding = 4 // 扩展预留
)

// Enum value maps for Encoding.
var (
	Encoding_name = map[int32]string{
		0: "ENCODING_UNSPECIFIED",
		1: "ENCODING_JSON",
		2: "ENCODING_PROTOBUF",
		3: "ENCODING_MSGPACK",
		4: "ENCODING_CBOR",
	}
	Encoding_value = map[string]int32{
		"ENCODING_UNSPECIFIED": 0,
		"ENCODING_JSON":        1,
		"ENCODING_PROTOBUF":    2,
		"ENCODING_MSGPACK":     3,
		"ENCODING_CBOR":        4,
	}
)

func (x Encoding) Enum() *Encoding {
	p := new(Encoding)
	*p = x
	return p
}

func (x Encoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Encoding) Descriptor() protoreflect.EnumDescriptor {
	return file_v2_common_proto_enumTypes[0].Descriptor()
}

func (Encoding) Type() protoreflect.EnumType {
	return &file_v2_common_proto_enumTypes[0]
}

func (x Encoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Encoding.Descriptor instead.
func (Encoding) EnumDescriptor() ([]byte, []int) {
	return file_v2_common_proto_rawDescGZIP(), []int{0}
}

// FrameFlags 定义帧标志位
type FrameFlags int32

const (
	FrameFlags_FLAG_NONE         FrameFlags = 0
	FrameFlags_FLAG_ACK_REQUIRED FrameFlags = 1  // 需要 ACK 确认
	FrameFlags_FLAG_IS_ACK       FrameFlags = 2  // 这是一个 ACK 响应
	FrameFlags_FLAG_IS_NACK      FrameFlags = 4  // 这是一个 NACK(否定确认)
	FrameFlags_FLAG_COMPRESSED   FrameFlags = 8  // Payload 已压缩(gzip)
	FrameFlags_FLAG_RETRANSMIT   FrameFlags = 16 // 这是重发的消息
	FrameFlags_FLAG_PRIORITY     FrameFlags = 32 // 优先级标志(高优先级)
)

// Enum value maps for FrameFlags.
var (
	FrameFlags_name = map[int32]string{
		0:  "FLAG_NONE",
		1:  "FLAG_ACK_REQUIRED",
		2:  "FLAG_IS_ACK",
		4:  "FLAG_IS_NACK",
		8:  "FLAG_COMPRESSED",
		16: "FLAG_RETRANSMIT",
		32: "FLAG_PRIORITY",
	}
	FrameFlags_value = map[string]int32{
		"FLAG_NONE":         0,
		"FLAG_ACK_REQUIRED": 1,
		"FLAG_IS_ACK":       2,
		"FLAG_IS_NACK":      4,
		"FLAG_COMPRESSED":   8,
		"FLAG_RETRANSMIT":   16,
		"FLAG_PRIORITY":     32,
	}
)

func (x FrameFlags) Enum() *FrameFlags {
	p := new(FrameFlags)
	*p = x
	return p
}

func (x FrameFlags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameFlags) Descriptor() protoreflect.EnumDescriptor {
	return file_v2_common_proto_enumTypes[1].Descriptor()
}

func (FrameFlags) Type() protoreflect.EnumType {
	return &file_v2_common_proto_enumTypes[1]
}

func (x FrameFlags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameFlags.Descriptor instead.
func (FrameFlags) EnumDescriptor() ([]byte, []int) {
	return file_v2_common_proto_rawDescGZIP(), []int{1}
}

// ErrorCode 定义错误码
type ErrorCode int32

const (
	ErrorCode_ERROR_UNKNOWN             ErrorCode = 0
	ErrorCode_ERROR_UNAUTHORIZED        ErrorCode = 1
	ErrorCode_ERROR_PERMISSION_DENIED   ErrorCode = 2
	ErrorCode_ERROR_INVALID_CHANNEL     ErrorCode = 3
	ErrorCode_ERROR_CHANNEL_LIMIT       ErrorCode = 4
	ErrorCode_ERROR_RATE_LIMIT          ErrorCode = 5
	ErrorCode_ERROR_INVALID_MESSAGE     ErrorCode = 6
	ErrorCode_ERROR_RPC_TIMEOUT         ErrorCode = 7
	ErrorCode_ERROR_RPC_NOT_FOUND       ErrorCode = 8
	ErrorCode_ERROR_INTERNAL            ErrorCode = 9
	ErrorCode_ERROR_SERVICE_UNAVAILABLE ErrorCode = 10
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_UNKNOWN",
		1:  "ERROR_UNAUTHORIZED",
		2:  "ERROR_PERMISSION_DENIED",
		3:  "ERROR_INVALID_CHANNEL",
		4:  "ERROR_CHANNEL_LIMIT",
		5:  "ERROR_RATE_LIMIT",
		6:  "ERROR_INVALID_MESSAGE",
		7:  "ERROR_RPC_TIMEOUT",
		8:  "ERROR_RPC_NOT_FOUND",
		9:  "ERROR_INTERNAL",
		10: "ERROR_SERVICE_UNAVAILABLE",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_UNKNOWN":             0,
		"ERROR_UNAUTHORIZED":        1,
		"ERROR_PERMISSION_DENIED":   2,
		"ERROR_INVALID_CHANNEL":     3,
		"ERROR_CHANNEL_LIMIT":       4,
		"ERROR_RATE_LIMIT":          5,
		"ERROR_INVALID_MESSAGE":     6,
		"ERROR_RPC_TIMEOUT":         7,
		"ERROR_RPC_NOT_FOUND":       8,
		"ERROR_INTERNAL":            9,
		"ERROR_SERVICE_UNAVAILABLE": 10,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_v2_common_proto_enumTypes[2].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_v2_common_proto_enumTypes[2]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_v2_common_proto_rawDescGZIP(), []int{2}
}

// DisconnectCode 定义断开连接原因码
type DisconnectCode int32

const (
	DisconnectCode_DISCONNECT_NORMAL           DisconnectCode = 0
	DisconnectCode_DISCONNECT_UNAUTHORIZED     DisconnectCode = 1
	DisconnectCode_DISCONNECT_TOKEN_EXPIRED    DisconnectCode = 2
	DisconnectCode_DISCONNECT_KICKED           DisconnectCode = 3
	DisconnectCode_DISCONNECT_PROTOCOL_ERROR   DisconnectCode = 10
	DisconnectCode_DISCONNECT_VERSION_MISMATCH DisconnectCode = 11
	DisconnectCode_DISCONNECT_TOO_MANY_ERRORS  DisconnectCode = 12
	DisconnectCode_DISCONNECT_IDLE_TIMEOUT     DisconnectCode = 20
	DisconnectCode_DISCONNECT_CONNECTION_LIMIT DisconnectCode = 21
	DisconnectCode_DISCONNECT_RATE_LIMIT       DisconnectCode = 22
	DisconnectCode_DISCONNECT_SERVER_SHUTDOWN  DisconnectCode = 30
	DisconnectCode_DISCONNECT_SERVER_RESTART   DisconnectCode = 31
	DisconnectCode_DISCONNECT_INTERNAL_ERROR   DisconnectCode = 32
)

// Enum value maps for DisconnectCode.
var (
	DisconnectCode_name = map[int32]string{
		0:  "DISCONNECT_NORMAL",
		1:  "DISCONNECT_UNAUTHORIZED",
		2:  "DISCONNECT_TOKEN_EXPIRED",
		3:  "DISCONNECT_KICKED",
		10: "DISCONNECT_PROTOCOL_ERROR",
		11: "DISCONNECT_VERSION_MISMATCH",
		12: "DISCONNECT_TOO_MANY_ERRORS",
		20: "DISCONNECT_IDLE_TIMEOUT",
		21: "DISCONNECT_CONNECTION_LIMIT",
		22: "DISCONNECT_RATE_LIMIT",
		30: "DISCONNECT_SERVER_SHUTDOWN",
		31: "DISCONNECT_SERVER_RESTART",
		32: "DISCONNECT_INTERNAL_ERROR",
	}
	DisconnectCode_value = map[string]int32{
		"DISCONNECT_NORMAL":           0,
		"DISCONNECT_UNAUTHORIZED":     1,
		"DISCONNECT_TOKEN_EXPIRED":    2,
		"DISCONNECT_KICKED":           3,
		"DISCONNECT_PROTOCOL_ERROR":   10,
		"DISCONNECT_VERSION_MISMATCH": 11,
		"DISCONNECT_TOO_MANY_ERRORS":  12,
		"DISCONNECT_IDLE_TIMEOUT":     20,
		"DISCONNECT_CONNECTION_LIMIT": 21,
		"DISCONNECT_RATE_LIMIT":       22,
		"DISCONNECT_SERVER_SHUTDOWN":  30,
		"DISCONNECT_SERVER_RESTART":   31,
		"DISCONNECT_INTERNAL_ERROR":   32,
	}
)

func (x DisconnectCode) Enum() *DisconnectCode {
	p := new(DisconnectCode)
	*p = x
	return p
}

func (x DisconnectCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DisconnectCode) Descriptor() protoreflect.EnumDescriptor {
	return file_v2_common_proto_enumTypes[3].Descriptor()
}

func (DisconnectCode) Type() protoreflect.EnumType {
	return &file_v2_common_proto_enumTypes[3]
}

func (x DisconnectCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DisconnectCode.Descriptor instead.
func (DisconnectCode) EnumDescriptor() ([]byte, []int) {
	return file_v2_common_proto_rawDescGZIP(), []int{3}
}

// StreamPosition 定义流位置(用于历史消息恢复)
type StreamPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"` // 偏移量
	Epoch         string                 `protobuf:"bytes,2,opt,name=epoch,proto3" json:"epoch,omitempty"`    // 纪元(用于检测流重置)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPosition) Reset() {
	*x = StreamPosition{}
	mi := &file_v2_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPosition) ProtoMessage() {}

func (x *StreamPosition) ProtoReflect() protoreflect.Message {
	mi := &file_v2_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPosition.ProtoReflect.Descriptor instead.
func (*StreamPosition) Descriptor() ([]byte, []int) {
	return file_v2_common_proto_rawDescGZIP(), []int{0}
}

func (x *StreamPosition) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *StreamPosition) GetEpoch() string {
	if x != nil {
		return x.Epoch
	}
	return ""
}

var File_v2_common_proto protoreflect.FileDescriptor

const file_v2_common_proto_rawDesc = "" +
	"\n" +
	"\x0fv2/common.proto\x12\x0emessageloop.v2\">\n" +
	"\x0eStreamPosition\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\tR\x05epoch*w\n" +
	"\bEncoding\x12\x18\n" +
	"\x14ENCODING_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rENCODING_JSON\x10\x01\x12\x15\n" +
	"\x11ENCODING_PROTOBUF\x10\x02\x12\x14\n" +
	"\x10ENCODING_MSGPACK\x10\x03\x12\x11\n" +
	"\rENCODING_CBOR\x10\x04*\x92\x01\n" +
	"\n" +
	"FrameFlags\x12\r\n" +
	"\tFLAG_NONE\x10\x00\x12\x15\n" +
	"\x11FLAG_ACK_REQUIRED\x10\x01\x12\x0f\n" +
	"\vFLAG_IS_ACK\x10\x02\x12\x10\n" +
	"\fFLAG_IS_NACK\x10\x04\x12\x13\n" +
	"\x0fFLAG_COMPRESSED\x10\b\x12\x13\n" +
	"\x0fFLAG_RETRANSMIT\x10\x10\x12\x11\n" +
	"\rFLAG_PRIORITY\x10 *\x9b\x02\n" +
	"\tErrorCode\x12\x11\n" +
	"\rERROR_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12ERROR_UNAUTHORIZED\x10\x01\x12\x1b\n" +
	"\x17ERROR_PERMISSION_DENIED\x10\x02\x12\x19\n" +
	"\x15ERROR_INVALID_CHANNEL\x10\x03\x12\x17\n" +
	"\x13ERROR_CHANNEL_LIMIT\x10\x04\x12\x14\n" +
	"\x10ERROR_RATE_LIMIT\x10\x05\x12\x19\n" +
	"\x15ERROR_INVALID_MESSAGE\x10\x06\x12\x15\n" +
	"\x11ERROR_RPC_TIMEOUT\x10\a\x12\x17\n" +
	"\x13ERROR_RPC_NOT_FOUND\x10\b\x12\x12\n" +
	"\x0eERROR_INTERNAL\x10\t\x12\x1d\n" +
	"\x19ERROR_SERVICE_UNAVAILABLE\x10\n" +
	"*\x90\x03\n" +
	"\x0eDisconnectCode\x12\x15\n" +
	"\x11DISCONNECT_NORMAL\x10\x00\x12\x1b\n" +
	"\x17DISCONNECT_UNAUTHORIZED\x10\x01\x12\x1c\n" +
	"\x18DISCONNECT_TOKEN_EXPIRED\x10\x02\x12\x15\n" +
	"\x11DISCONNECT_KICKED\x10\x03\x12\x1d\n" +
	"\x19DISCONNECT_PROTOCOL_ERROR\x10\n" +
	"\x12\x1f\n" +
	"\x1bDISCONNECT_VERSION_MISMATCH\x10\v\x12\x1e\n" +
	"\x1aDISCONNECT_TOO_MANY_ERRORS\x10\f\x12\x1b\n" +
	"\x17DISCONNECT_IDLE_TIMEOUT\x10\x14\x12\x1f\n" +
	"\x1bDISCONNECT_CONNECTION_LIMIT\x10\x15\x12\x19\n" +
	"\x15DISCONNECT_RATE_LIMIT\x10\x16\x12\x1e\n" +
	"\x1aDISCONNECT_SERVER_SHUTDOWN\x10\x1e\x12\x1d\n" +
	"\x19DISCONNECT_SERVER_RESTART\x10\x1f\x12\x1d\n" +
	"\x19DISCONNECT_INTERNAL_ERROR\x10 B<Z:github.com/messageloopio/messageloop/shared/genproto/v2;v2b\x06proto3"

var (
	file_v2_common_proto_rawDescOnce sync.Once
	file_v2_common_proto_rawDescData []byte
)

func file_v2_common_proto_rawDescGZIP() []byte {
	file_v2_common_proto_rawDescOnce.Do(func() {
		file_v2_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_common_proto_rawDesc), len(file_v2_common_proto_rawDesc)))
	})
	return file_v2_common_proto_rawDescData
}

var file_v2_common_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_v2_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v2_common_proto_goTypes = []any{
	(Encoding)(0),          // 0: messageloop.v2.Encoding
	(FrameFlags)(0),        // 1: messageloop.v2.FrameFlags
	(ErrorCode)(0),         // 2: messageloop.v2.ErrorCode
	(DisconnectCode)(0),    // 3: messageloop.v2.DisconnectCode
	(*StreamPosition)(nil), // 4: messageloop.v2.StreamPosition
}
var file_v2_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v2_common_proto_init() }
func file_v2_common_proto_init() {
	if File_v2_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_common_proto_rawDesc), len(file_v2_common_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_common_proto_goTypes,
		DependencyIndexes: file_v2_common_proto_depIdxs,
		EnumInfos:         file_v2_common_proto_enumTypes,
		MessageInfos:      file_v2_common_proto_msgTypes,
	}.Build()
	File_v2_common_proto = out.File
	file_v2_common_proto_goTypes = nil
	file_v2_common_proto_depIdxs = nil
}
