// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v2/frame.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Frame 是协议的核心传输单元
// 负责消息边界、ID 生成、ACK、去重、编码协商
type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 服务端生成的全局唯一 ID（UUID 字符串）
	FrameId string `protobuf:"bytes,1,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	// 会话 ID（服务端在 Connect 时生成）
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// 客户端递增序列号（用于去重和顺序保证）
	ClientSeq uint64 `protobuf:"varint,3,opt,name=client_seq,json=clientSeq,proto3" json:"client_seq,omitempty"`
	// Unix 毫秒时间戳（服务端生成）
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Frame 类型标志位（使用 FrameFlags 枚举值的组合）
	Flags uint32 `protobuf:"varint,5,opt,name=flags,proto3" json:"flags,omitempty"`
	// 编码类型
	Encoding Encoding `protobuf:"varint,6,opt,name=encoding,proto3,enum=messageloop.v2.Encoding" json:"encoding,omitempty"`
	// 应用层消息（编码后的字节）
	Payload       []byte `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_v2_frame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_v2_frame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_v2_frame_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

func (x *Frame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Frame) GetClientSeq() uint64 {
	if x != nil {
		return x.ClientSeq
	}
	return 0
}

func (x *Frame) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Frame) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Frame) GetEncoding() Encoding {
	if x != nil {
		return x.Encoding
	}
	return Encoding_ENCODING_UNSPECIFIED
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_v2_frame_proto protoreflect.FileDescriptor

const file_v2_frame_proto_rawDesc = "" +
	"\n" +
	"\x0ev2/frame.proto\x12\x0emessageloop.v2\x1a\x0fv2/common.proto\"\xe4\x01\n" +
	"\x05Frame\x12\x19\n" +
	"\bframe_id\x18\x01 \x01(\tR\aframeId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"client_seq\x18\x03 \x01(\x04R\tclientSeq\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05flags\x18\x05 \x01(\rR\x05flags\x124\n" +
	"\bencoding\x18\x06 \x01(\x0e2\x18.messageloop.v2.EncodingR\bencoding\x12\x18\n" +
	"\apayload\x18\n" +
	" \x01(\fR\apayloadB<Z:github.com/messageloopio/messageloop/shared/genproto/v2;v2b\x06proto3"

var (
	file_v2_frame_proto_rawDescOnce sync.Once
	file_v2_frame_proto_rawDescData []byte
)

func file_v2_frame_proto_rawDescGZIP() []byte {
	file_v2_frame_proto_rawDescOnce.Do(func() {
		file_v2_frame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_frame_proto_rawDesc), len(file_v2_frame_proto_rawDesc)))
	})
	return file_v2_frame_proto_rawDescData
}

var file_v2_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v2_frame_proto_goTypes = []any{
	(*Frame)(nil), // 0: messageloop.v2.Frame
	(Encoding)(0), // 1: messageloop.v2.Encoding
}
var file_v2_frame_proto_depIdxs = []int32{
	1, // 0: messageloop.v2.Frame.encoding:type_name -> messageloop.v2.Encoding
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v2_frame_proto_init() }
func file_v2_frame_proto_init() {
	if File_v2_frame_proto != nil {
		return
	}
	file_v2_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_frame_proto_rawDesc), len(file_v2_frame_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_frame_proto_goTypes,
		DependencyIndexes: file_v2_frame_proto_depIdxs,
		MessageInfos:      file_v2_frame_proto_msgTypes,
	}.Build()
	File_v2_frame_proto = out.File
	file_v2_frame_proto_goTypes = nil
	file_v2_frame_proto_depIdxs = nil
}
