// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v2/service.proto

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamFrame is the raw byte carrier for the v2 gRPC streaming transport.
// It wraps an already-encoded Frame (Protobuf or JSON bytes) to avoid
// double-encoding — gRPC carries it as an opaque payload.
type StreamFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFrame) Reset() {
	*x = StreamFrame{}
	mi := &file_v2_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFrame) ProtoMessage() {}

func (x *StreamFrame) ProtoReflect() protoreflect.Message {
	mi := &file_v2_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFrame.ProtoReflect.Descriptor instead.
func (*StreamFrame) Descriptor() ([]byte, []int) {
	return file_v2_service_proto_rawDescGZIP(), []int{0}
}

func (x *StreamFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_v2_service_proto protoreflect.FileDescriptor

const file_v2_service_proto_rawDesc = "" +
	"\n" +
	"\x10v2/service.proto\x12\x0emessageloop.v2\"!\n" +
	"\vStreamFrame\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2a\n" +
	"\x12MessagingServiceV2\x12K\n" +
	"\vMessageLoop\x12\x1b.messageloop.v2.StreamFrame\x1a\x1b.messageloop.v2.StreamFrame(\x010\x01B<Z:github.com/messageloopio/messageloop/shared/genproto/v2;v2b\x06proto3"

var (
	file_v2_service_proto_rawDescOnce sync.Once
	file_v2_service_proto_rawDescData []byte
)

func file_v2_service_proto_rawDescGZIP() []byte {
	file_v2_service_proto_rawDescOnce.Do(func() {
		file_v2_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_service_proto_rawDesc), len(file_v2_service_proto_rawDesc)))
	})
	return file_v2_service_proto_rawDescData
}

var file_v2_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v2_service_proto_goTypes = []any{
	(*StreamFrame)(nil), // 0: messageloop.v2.StreamFrame
}
var file_v2_service_proto_depIdxs = []int32{
	0, // 0: messageloop.v2.MessagingServiceV2.MessageLoop:input_type -> messageloop.v2.StreamFrame
	0, // 1: messageloop.v2.MessagingServiceV2.MessageLoop:output_type -> messageloop.v2.StreamFrame
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v2_service_proto_init() }
func file_v2_service_proto_init() {
	if File_v2_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_service_proto_rawDesc), len(file_v2_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v2_service_proto_goTypes,
		DependencyIndexes: file_v2_service_proto_depIdxs,
		MessageInfos:      file_v2_service_proto_msgTypes,
	}.Build()
	File_v2_service_proto = out.File
	file_v2_service_proto_goTypes = nil
	file_v2_service_proto_depIdxs = nil
}
