// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: client/v2/service.proto

package clientv2

import (
	v2 "github.com/messageloopio/messageloop/shared/genproto/shared/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecoverState int32

const (
	RecoverState_RECOVER_STATE_UNSPECIFIED RecoverState = 0
	RecoverState_RECOVER_STATE_NONE        RecoverState = 1
	RecoverState_RECOVER_STATE_PENDING     RecoverState = 2
	RecoverState_RECOVER_STATE_SKIPPED     RecoverState = 3
	RecoverState_RECOVER_STATE_FAILED      RecoverState = 4
)

// Enum value maps for RecoverState.
var (
	RecoverState_name = map[int32]string{
		0: "RECOVER_STATE_UNSPECIFIED",
		1: "RECOVER_STATE_NONE",
		2: "RECOVER_STATE_PENDING",
		3: "RECOVER_STATE_SKIPPED",
		4: "RECOVER_STATE_FAILED",
	}
	RecoverState_value = map[string]int32{
		"RECOVER_STATE_UNSPECIFIED": 0,
		"RECOVER_STATE_NONE":        1,
		"RECOVER_STATE_PENDING":     2,
		"RECOVER_STATE_SKIPPED":     3,
		"RECOVER_STATE_FAILED":      4,
	}
)

func (x RecoverState) Enum() *RecoverState {
	p := new(RecoverState)
	*p = x
	return p
}

func (x RecoverState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecoverState) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v2_service_proto_enumTypes[0].Descriptor()
}

func (RecoverState) Type() protoreflect.EnumType {
	return &file_client_v2_service_proto_enumTypes[0]
}

func (x RecoverState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecoverState.Descriptor instead.
func (RecoverState) EnumDescriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{0}
}

// 客户端 -> 服务端
type InboundMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Time  uint64                 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	// Types that are valid to be assigned to Envelope:
	//
	//	*InboundMessage_Connect
	//	*InboundMessage_Subscribe
	//	*InboundMessage_Unsubscribe
	//	*InboundMessage_Publish
	//	*InboundMessage_RpcRequest
	//	*InboundMessage_SubRefresh
	//	*InboundMessage_SurveyRequest
	//	*InboundMessage_SurveyReply
	//	*InboundMessage_Ping
	//	*InboundMessage_Pong
	//	*InboundMessage_PresenceQuery
	Envelope      isInboundMessage_Envelope `protobuf_oneof:"envelope"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundMessage) Reset() {
	*x = InboundMessage{}
	mi := &file_client_v2_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundMessage) ProtoMessage() {}

func (x *InboundMessage) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundMessage.ProtoReflect.Descriptor instead.
func (*InboundMessage) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{0}
}

func (x *InboundMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InboundMessage) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *InboundMessage) GetEnvelope() isInboundMessage_Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *InboundMessage) GetConnect() *Connect {
	if x != nil {
		if x, ok := x.Envelope.(*InboundMessage_Connect); ok {
			return x.Connect
		}
	}
	return nil
}

func (x *InboundMessage) GetSubscribe() *Subscribe {
	if x != nil {
		if x, ok := x.Envelope.(*InboundMessage_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *InboundMessage) GetUnsubscribe() *Unsubscribe {
	if x != nil {
		if x, ok := x.Envelope.(*InboundMessage_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

func (x *InboundMessage) GetPublish() *Publish {
	if x != nil {
		if x, ok := x.Envelope.(*InboundMessage_Publish); ok {
			return x.Publish
		}
	}
	return nil
}

func (x *InboundMessage) GetRpcRequest() *RpcRequest {
	if x != nil {
		if x, ok := x.Envelope.(*InboundMessage_RpcRequest); ok {
			return x.RpcRequest
		}
	}
	return nil
}

func (x *InboundMessage) GetSubRefresh() *SubRefresh {
	if x != nil {
		if x, ok := x.Envelope.(*InboundMessage_SubRefresh); ok {
			return x.SubRefresh
		}
	}
	return nil
}

func (x *InboundMessage) GetSurveyRequest() *SurveyRequest {
	if x != nil {
		if x, ok := x.Envelope.(*InboundMessage_SurveyRequest); ok {
			return x.SurveyRequest
		}
	}
	return nil
}

func (x *InboundMessage) GetSurveyReply() *SurveyReply {
	if x != nil {
		if x, ok := x.Envelope.(*InboundMessage_SurveyReply); ok {
			return x.SurveyReply
		}
	}
	return nil
}

func (x *InboundMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Envelope.(*InboundMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *InboundMessage) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Envelope.(*InboundMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *InboundMessage) GetPresenceQuery() *PresenceQuery {
	if x != nil {
		if x, ok := x.Envelope.(*InboundMessage_PresenceQuery); ok {
			return x.PresenceQuery
		}
	}
	return nil
}

type isInboundMessage_Envelope interface {
	isInboundMessage_Envelope()
}

type InboundMessage_Connect struct {
	Connect *Connect `protobuf:"bytes,3,opt,name=connect,proto3,oneof"`
}

type InboundMessage_Subscribe struct {
	Subscribe *Subscribe `protobuf:"bytes,4,opt,name=subscribe,proto3,oneof"`
}

type InboundMessage_Unsubscribe struct {
	Unsubscribe *Unsubscribe `protobuf:"bytes,5,opt,name=unsubscribe,proto3,oneof"`
}

type InboundMessage_Publish struct {
	Publish *Publish `protobuf:"bytes,6,opt,name=publish,proto3,oneof"`
}

type InboundMessage_RpcRequest struct {
	RpcRequest *RpcRequest `protobuf:"bytes,7,opt,name=rpc_request,json=rpcRequest,proto3,oneof"`
}

type InboundMessage_SubRefresh struct {
	SubRefresh *SubRefresh `protobuf:"bytes,8,opt,name=sub_refresh,json=subRefresh,proto3,oneof"`
}

type InboundMessage_SurveyRequest struct {
	SurveyRequest *SurveyRequest `protobuf:"bytes,9,opt,name=survey_request,json=surveyRequest,proto3,oneof"`
}

type InboundMessage_SurveyReply struct {
	SurveyReply *SurveyReply `protobuf:"bytes,10,opt,name=survey_reply,json=surveyReply,proto3,oneof"`
}

type InboundMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,11,opt,name=ping,proto3,oneof"`
}

type InboundMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,12,opt,name=pong,proto3,oneof"`
}

type InboundMessage_PresenceQuery struct {
	PresenceQuery *PresenceQuery `protobuf:"bytes,13,opt,name=presence_query,json=presenceQuery,proto3,oneof"`
}

func (*InboundMessage_Connect) isInboundMessage_Envelope() {}

func (*InboundMessage_Subscribe) isInboundMessage_Envelope() {}

func (*InboundMessage_Unsubscribe) isInboundMessage_Envelope() {}

func (*InboundMessage_Publish) isInboundMessage_Envelope() {}

func (*InboundMessage_RpcRequest) isInboundMessage_Envelope() {}

func (*InboundMessage_SubRefresh) isInboundMessage_Envelope() {}

func (*InboundMessage_SurveyRequest) isInboundMessage_Envelope() {}

func (*InboundMessage_SurveyReply) isInboundMessage_Envelope() {}

func (*InboundMessage_Ping) isInboundMessage_Envelope() {}

func (*InboundMessage_Pong) isInboundMessage_Envelope() {}

func (*InboundMessage_PresenceQuery) isInboundMessage_Envelope() {}

// 服务端 -> 客户端
type OutboundMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Time  uint64                 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	// Types that are valid to be assigned to Envelope:
	//
	//	*OutboundMessage_Error
	//	*OutboundMessage_Connected
	//	*OutboundMessage_SubscribeAck
	//	*OutboundMessage_UnsubscribeAck
	//	*OutboundMessage_PublishAck
	//	*OutboundMessage_Publication
	//	*OutboundMessage_RecoverComplete
	//	*OutboundMessage_RpcReply
	//	*OutboundMessage_SubRefreshAck
	//	*OutboundMessage_SurveyRequest
	//	*OutboundMessage_SurveyReply
	//	*OutboundMessage_SurveyResult
	//	*OutboundMessage_Presence
	//	*OutboundMessage_PresenceEvent
	//	*OutboundMessage_Ping
	//	*OutboundMessage_Pong
	Envelope      isOutboundMessage_Envelope `protobuf_oneof:"envelope"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundMessage) Reset() {
	*x = OutboundMessage{}
	mi := &file_client_v2_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundMessage) ProtoMessage() {}

func (x *OutboundMessage) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundMessage.ProtoReflect.Descriptor instead.
func (*OutboundMessage) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{1}
}

func (x *OutboundMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OutboundMessage) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *OutboundMessage) GetEnvelope() isOutboundMessage_Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *OutboundMessage) GetError() *v2.Error {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *OutboundMessage) GetConnected() *Connected {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_Connected); ok {
			return x.Connected
		}
	}
	return nil
}

func (x *OutboundMessage) GetSubscribeAck() *SubscribeAck {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_SubscribeAck); ok {
			return x.SubscribeAck
		}
	}
	return nil
}

func (x *OutboundMessage) GetUnsubscribeAck() *UnsubscribeAck {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_UnsubscribeAck); ok {
			return x.UnsubscribeAck
		}
	}
	return nil
}

func (x *OutboundMessage) GetPublishAck() *PublishAck {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_PublishAck); ok {
			return x.PublishAck
		}
	}
	return nil
}

func (x *OutboundMessage) GetPublication() *Publication {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_Publication); ok {
			return x.Publication
		}
	}
	return nil
}

func (x *OutboundMessage) GetRecoverComplete() *RecoverComplete {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_RecoverComplete); ok {
			return x.RecoverComplete
		}
	}
	return nil
}

func (x *OutboundMessage) GetRpcReply() *RpcReply {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_RpcReply); ok {
			return x.RpcReply
		}
	}
	return nil
}

func (x *OutboundMessage) GetSubRefreshAck() *SubRefreshAck {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_SubRefreshAck); ok {
			return x.SubRefreshAck
		}
	}
	return nil
}

func (x *OutboundMessage) GetSurveyRequest() *SurveyRequest {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_SurveyRequest); ok {
			return x.SurveyRequest
		}
	}
	return nil
}

func (x *OutboundMessage) GetSurveyReply() *SurveyReply {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_SurveyReply); ok {
			return x.SurveyReply
		}
	}
	return nil
}

func (x *OutboundMessage) GetSurveyResult() *SurveyResult {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_SurveyResult); ok {
			return x.SurveyResult
		}
	}
	return nil
}

func (x *OutboundMessage) GetPresence() *PresenceSnapshot {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_Presence); ok {
			return x.Presence
		}
	}
	return nil
}

func (x *OutboundMessage) GetPresenceEvent() *PresenceEvent {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_PresenceEvent); ok {
			return x.PresenceEvent
		}
	}
	return nil
}

func (x *OutboundMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *OutboundMessage) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Envelope.(*OutboundMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isOutboundMessage_Envelope interface {
	isOutboundMessage_Envelope()
}

type OutboundMessage_Error struct {
	Error *v2.Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type OutboundMessage_Connected struct {
	Connected *Connected `protobuf:"bytes,4,opt,name=connected,proto3,oneof"`
}

type OutboundMessage_SubscribeAck struct {
	SubscribeAck *SubscribeAck `protobuf:"bytes,5,opt,name=subscribe_ack,json=subscribeAck,proto3,oneof"`
}

type OutboundMessage_UnsubscribeAck struct {
	UnsubscribeAck *UnsubscribeAck `protobuf:"bytes,6,opt,name=unsubscribe_ack,json=unsubscribeAck,proto3,oneof"`
}

type OutboundMessage_PublishAck struct {
	PublishAck *PublishAck `protobuf:"bytes,7,opt,name=publish_ack,json=publishAck,proto3,oneof"`
}

type OutboundMessage_Publication struct {
	Publication *Publication `protobuf:"bytes,8,opt,name=publication,proto3,oneof"`
}

type OutboundMessage_RecoverComplete struct {
	RecoverComplete *RecoverComplete `protobuf:"bytes,9,opt,name=recover_complete,json=recoverComplete,proto3,oneof"`
}

type OutboundMessage_RpcReply struct {
	RpcReply *RpcReply `protobuf:"bytes,10,opt,name=rpc_reply,json=rpcReply,proto3,oneof"`
}

type OutboundMessage_SubRefreshAck struct {
	SubRefreshAck *SubRefreshAck `protobuf:"bytes,11,opt,name=sub_refresh_ack,json=subRefreshAck,proto3,oneof"`
}

type OutboundMessage_SurveyRequest struct {
	SurveyRequest *SurveyRequest `protobuf:"bytes,12,opt,name=survey_request,json=surveyRequest,proto3,oneof"`
}

type OutboundMessage_SurveyReply struct {
	SurveyReply *SurveyReply `protobuf:"bytes,13,opt,name=survey_reply,json=surveyReply,proto3,oneof"`
}

type OutboundMessage_SurveyResult struct {
	SurveyResult *SurveyResult `protobuf:"bytes,14,opt,name=survey_result,json=surveyResult,proto3,oneof"`
}

type OutboundMessage_Presence struct {
	Presence *PresenceSnapshot `protobuf:"bytes,15,opt,name=presence,proto3,oneof"`
}

type OutboundMessage_PresenceEvent struct {
	PresenceEvent *PresenceEvent `protobuf:"bytes,16,opt,name=presence_event,json=presenceEvent,proto3,oneof"`
}

type OutboundMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,17,opt,name=ping,proto3,oneof"`
}

type OutboundMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,18,opt,name=pong,proto3,oneof"`
}

func (*OutboundMessage_Error) isOutboundMessage_Envelope() {}

func (*OutboundMessage_Connected) isOutboundMessage_Envelope() {}

func (*OutboundMessage_SubscribeAck) isOutboundMessage_Envelope() {}

func (*OutboundMessage_UnsubscribeAck) isOutboundMessage_Envelope() {}

func (*OutboundMessage_PublishAck) isOutboundMessage_Envelope() {}

func (*OutboundMessage_Publication) isOutboundMessage_Envelope() {}

func (*OutboundMessage_RecoverComplete) isOutboundMessage_Envelope() {}

func (*OutboundMessage_RpcReply) isOutboundMessage_Envelope() {}

func (*OutboundMessage_SubRefreshAck) isOutboundMessage_Envelope() {}

func (*OutboundMessage_SurveyRequest) isOutboundMessage_Envelope() {}

func (*OutboundMessage_SurveyReply) isOutboundMessage_Envelope() {}

func (*OutboundMessage_SurveyResult) isOutboundMessage_Envelope() {}

func (*OutboundMessage_Presence) isOutboundMessage_Envelope() {}

func (*OutboundMessage_PresenceEvent) isOutboundMessage_Envelope() {}

func (*OutboundMessage_Ping) isOutboundMessage_Envelope() {}

func (*OutboundMessage_Pong) isOutboundMessage_Envelope() {}

type Connect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientType    string                 `protobuf:"bytes,2,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Subscriptions []*Subscription        `protobuf:"bytes,5,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 上次会话 ID，为空表示新连接
	Caps          []string               `protobuf:"bytes,7,rep,name=caps,proto3" json:"caps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connect) Reset() {
	*x = Connect{}
	mi := &file_client_v2_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connect) ProtoMessage() {}

func (x *Connect) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connect.ProtoReflect.Descriptor instead.
func (*Connect) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{2}
}

func (x *Connect) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Connect) GetClientType() string {
	if x != nil {
		return x.ClientType
	}
	return ""
}

func (x *Connect) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Connect) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Connect) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *Connect) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Connect) GetCaps() []string {
	if x != nil {
		return x.Caps
	}
	return nil
}

type Connected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Subscriptions []*Subscription        `protobuf:"bytes,2,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`                // 必须带回 ephemeral
	Resumed       bool                   `protobuf:"varint,3,opt,name=resumed,proto3" json:"resumed,omitempty"`                           // 是否成功恢复会话
	StreamEpoch   string                 `protobuf:"bytes,4,opt,name=stream_epoch,json=streamEpoch,proto3" json:"stream_epoch,omitempty"` // broker 实例标识，用于防止重启后 offset 混淆
	AcceptedCaps  []string               `protobuf:"bytes,5,rep,name=accepted_caps,json=acceptedCaps,proto3" json:"accepted_caps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connected) Reset() {
	*x = Connected{}
	mi := &file_client_v2_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connected) ProtoMessage() {}

func (x *Connected) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connected.ProtoReflect.Descriptor instead.
func (*Connected) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{3}
}

func (x *Connected) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Connected) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *Connected) GetResumed() bool {
	if x != nil {
		return x.Resumed
	}
	return false
}

func (x *Connected) GetStreamEpoch() string {
	if x != nil {
		return x.StreamEpoch
	}
	return ""
}

func (x *Connected) GetAcceptedCaps() []string {
	if x != nil {
		return x.AcceptedCaps
	}
	return nil
}

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Ephemeral     bool                   `protobuf:"varint,2,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Recover       bool                   `protobuf:"varint,4,opt,name=recover,proto3" json:"recover,omitempty"` // 是否需要恢复离线消息
	Cursor        *v2.Position           `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`    // 恢复起点提示；unset 表示无提示
	Fresh         bool                   `protobuf:"varint,6,opt,name=fresh,proto3" json:"fresh,omitempty"`     // 显式从头；禁止用 cursor.offset==0 表示从头
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_client_v2_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{4}
}

func (x *Subscription) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Subscription) GetEphemeral() bool {
	if x != nil {
		return x.Ephemeral
	}
	return false
}

func (x *Subscription) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Subscription) GetRecover() bool {
	if x != nil {
		return x.Recover
	}
	return false
}

func (x *Subscription) GetCursor() *v2.Position {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *Subscription) GetFresh() bool {
	if x != nil {
		return x.Fresh
	}
	return false
}

type Subscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_client_v2_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{5}
}

func (x *Subscribe) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type SubscribeAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Recover       RecoverState           `protobuf:"varint,2,opt,name=recover,proto3,enum=messageloop.client.v2.RecoverState" json:"recover,omitempty"` // 批量里任一频道 pending 则 PENDING
	StreamEpoch   string                 `protobuf:"bytes,3,opt,name=stream_epoch,json=streamEpoch,proto3" json:"stream_epoch,omitempty"`
	Presence      []*PresenceSnapshot    `protobuf:"bytes,4,rep,name=presence,proto3" json:"presence,omitempty"` // 仅精确且非 ephemeral
	Error         *v2.Error              `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`       // 仅 recover=FAILED 时
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeAck) Reset() {
	*x = SubscribeAck{}
	mi := &file_client_v2_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeAck) ProtoMessage() {}

func (x *SubscribeAck) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeAck.ProtoReflect.Descriptor instead.
func (*SubscribeAck) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeAck) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *SubscribeAck) GetRecover() RecoverState {
	if x != nil {
		return x.Recover
	}
	return RecoverState_RECOVER_STATE_UNSPECIFIED
}

func (x *SubscribeAck) GetStreamEpoch() string {
	if x != nil {
		return x.StreamEpoch
	}
	return ""
}

func (x *SubscribeAck) GetPresence() []*PresenceSnapshot {
	if x != nil {
		return x.Presence
	}
	return nil
}

func (x *SubscribeAck) GetError() *v2.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Unsubscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unsubscribe) Reset() {
	*x = Unsubscribe{}
	mi := &file_client_v2_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unsubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unsubscribe) ProtoMessage() {}

func (x *Unsubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unsubscribe.ProtoReflect.Descriptor instead.
func (*Unsubscribe) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{7}
}

func (x *Unsubscribe) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type UnsubscribeAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeAck) Reset() {
	*x = UnsubscribeAck{}
	mi := &file_client_v2_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeAck) ProtoMessage() {}

func (x *UnsubscribeAck) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeAck.ProtoReflect.Descriptor instead.
func (*UnsubscribeAck) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{8}
}

func (x *UnsubscribeAck) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type RecoverComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Position      *v2.Position           `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Truncated     bool                   `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
	Gap           bool                   `protobuf:"varint,4,opt,name=gap,proto3" json:"gap,omitempty"`
	GapReason     v2.GapReason           `protobuf:"varint,5,opt,name=gap_reason,json=gapReason,proto3,enum=messageloop.shared.v2.GapReason" json:"gap_reason,omitempty"`
	Error         *v2.Error              `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"` // SKIPPED/FAILED 细节
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoverComplete) Reset() {
	*x = RecoverComplete{}
	mi := &file_client_v2_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverComplete) ProtoMessage() {}

func (x *RecoverComplete) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverComplete.ProtoReflect.Descriptor instead.
func (*RecoverComplete) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{9}
}

func (x *RecoverComplete) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *RecoverComplete) GetPosition() *v2.Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *RecoverComplete) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *RecoverComplete) GetGap() bool {
	if x != nil {
		return x.Gap
	}
	return false
}

func (x *RecoverComplete) GetGapReason() v2.GapReason {
	if x != nil {
		return x.GapReason
	}
	return v2.GapReason(0)
}

func (x *RecoverComplete) GetError() *v2.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Publish struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Channel        string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Payload        *v2.Payload            `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata       *v2.Metadata           `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Token          string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Transient      bool                   `protobuf:"varint,5,opt,name=transient,proto3" json:"transient,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Publish) Reset() {
	*x = Publish{}
	mi := &file_client_v2_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Publish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publish) ProtoMessage() {}

func (x *Publish) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publish.ProtoReflect.Descriptor instead.
func (*Publish) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{10}
}

func (x *Publish) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Publish) GetPayload() *v2.Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Publish) GetMetadata() *v2.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Publish) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Publish) GetTransient() bool {
	if x != nil {
		return x.Transient
	}
	return false
}

func (x *Publish) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type PublishAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             // 消息 ID，便于追踪
	Position      *v2.Position           `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"` // transient / 无历史 → offset 缺省
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishAck) Reset() {
	*x = PublishAck{}
	mi := &file_client_v2_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishAck) ProtoMessage() {}

func (x *PublishAck) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishAck.ProtoReflect.Descriptor instead.
func (*PublishAck) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{11}
}

func (x *PublishAck) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublishAck) GetPosition() *v2.Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Position      *v2.Position           `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Payload       *v2.Payload            `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      *v2.Metadata           `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Replay        bool                   `protobuf:"varint,6,opt,name=replay,proto3" json:"replay,omitempty"` // 恢复流回放
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_client_v2_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{12}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Message) GetPosition() *v2.Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Message) GetPayload() *v2.Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetMetadata() *v2.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Message) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

type Publication struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Publication) Reset() {
	*x = Publication{}
	mi := &file_client_v2_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Publication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publication) ProtoMessage() {}

func (x *Publication) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publication.ProtoReflect.Descriptor instead.
func (*Publication) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{13}
}

func (x *Publication) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type RpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Payload       *v2.Payload            `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      *v2.Metadata           `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcRequest) Reset() {
	*x = RpcRequest{}
	mi := &file_client_v2_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRequest) ProtoMessage() {}

func (x *RpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRequest.ProtoReflect.Descriptor instead.
func (*RpcRequest) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{14}
}

func (x *RpcRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *RpcRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RpcRequest) GetPayload() *v2.Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RpcRequest) GetMetadata() *v2.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RpcReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Payload       *v2.Payload            `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      *v2.Metadata           `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Error         *v2.Error              `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcReply) Reset() {
	*x = RpcReply{}
	mi := &file_client_v2_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcReply) ProtoMessage() {}

func (x *RpcReply) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcReply.ProtoReflect.Descriptor instead.
func (*RpcReply) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{15}
}

func (x *RpcReply) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RpcReply) GetPayload() *v2.Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RpcReply) GetMetadata() *v2.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RpcReply) GetError() *v2.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type SubRefresh struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []string               `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubRefresh) Reset() {
	*x = SubRefresh{}
	mi := &file_client_v2_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubRefresh) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubRefresh) ProtoMessage() {}

func (x *SubRefresh) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubRefresh.ProtoReflect.Descriptor instead.
func (*SubRefresh) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{16}
}

func (x *SubRefresh) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

type SubRefreshAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubRefreshAck) Reset() {
	*x = SubRefreshAck{}
	mi := &file_client_v2_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubRefreshAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubRefreshAck) ProtoMessage() {}

func (x *SubRefreshAck) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubRefreshAck.ProtoReflect.Descriptor instead.
func (*SubRefreshAck) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{17}
}

type SurveyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Payload       *v2.Payload            `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      *v2.Metadata           `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurveyRequest) Reset() {
	*x = SurveyRequest{}
	mi := &file_client_v2_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurveyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurveyRequest) ProtoMessage() {}

func (x *SurveyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurveyRequest.ProtoReflect.Descriptor instead.
func (*SurveyRequest) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{18}
}

func (x *SurveyRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SurveyRequest) GetPayload() *v2.Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SurveyRequest) GetMetadata() *v2.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SurveyRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *SurveyRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type SurveyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Payload       *v2.Payload            `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      *v2.Metadata           `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Error         *v2.Error              `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurveyReply) Reset() {
	*x = SurveyReply{}
	mi := &file_client_v2_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurveyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurveyReply) ProtoMessage() {}

func (x *SurveyReply) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurveyReply.ProtoReflect.Descriptor instead.
func (*SurveyReply) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{19}
}

func (x *SurveyReply) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SurveyReply) GetPayload() *v2.Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SurveyReply) GetMetadata() *v2.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SurveyReply) GetError() *v2.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// 客户端 Survey 汇总。与 server.v2.SurveyResult 同名不同包。
type SurveyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Answers       []*SurveyAnswer        `protobuf:"bytes,3,rep,name=answers,proto3" json:"answers,omitempty"`
	Error         *v2.Error              `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurveyResult) Reset() {
	*x = SurveyResult{}
	mi := &file_client_v2_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurveyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurveyResult) ProtoMessage() {}

func (x *SurveyResult) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurveyResult.ProtoReflect.Descriptor instead.
func (*SurveyResult) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{20}
}

func (x *SurveyResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SurveyResult) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *SurveyResult) GetAnswers() []*SurveyAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *SurveyResult) GetError() *v2.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type SurveyAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Payload       *v2.Payload            `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      *v2.Metadata           `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Error         *v2.Error              `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurveyAnswer) Reset() {
	*x = SurveyAnswer{}
	mi := &file_client_v2_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurveyAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurveyAnswer) ProtoMessage() {}

func (x *SurveyAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurveyAnswer.ProtoReflect.Descriptor instead.
func (*SurveyAnswer) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{21}
}

func (x *SurveyAnswer) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SurveyAnswer) GetPayload() *v2.Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SurveyAnswer) GetMetadata() *v2.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SurveyAnswer) GetError() *v2.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type PresenceQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"` // 精确频道
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceQuery) Reset() {
	*x = PresenceQuery{}
	mi := &file_client_v2_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceQuery) ProtoMessage() {}

func (x *PresenceQuery) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceQuery.ProtoReflect.Descriptor instead.
func (*PresenceQuery) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{22}
}

func (x *PresenceQuery) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type PresenceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // Connect.client_id（设备/端），不是 session
	ConnectedAt   int64                  `protobuf:"varint,4,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceInfo) Reset() {
	*x = PresenceInfo{}
	mi := &file_client_v2_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceInfo) ProtoMessage() {}

func (x *PresenceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceInfo.ProtoReflect.Descriptor instead.
func (*PresenceInfo) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{23}
}

func (x *PresenceInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PresenceInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PresenceInfo) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PresenceInfo) GetConnectedAt() int64 {
	if x != nil {
		return x.ConnectedAt
	}
	return 0
}

type PresenceSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Clients       []*PresenceInfo        `protobuf:"bytes,2,rep,name=clients,proto3" json:"clients,omitempty"`
	Truncated     bool                   `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
	Occupancy     int32                  `protobuf:"varint,4,opt,name=occupancy,proto3" json:"occupancy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceSnapshot) Reset() {
	*x = PresenceSnapshot{}
	mi := &file_client_v2_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceSnapshot) ProtoMessage() {}

func (x *PresenceSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceSnapshot.ProtoReflect.Descriptor instead.
func (*PresenceSnapshot) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{24}
}

func (x *PresenceSnapshot) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PresenceSnapshot) GetClients() []*PresenceInfo {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *PresenceSnapshot) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *PresenceSnapshot) GetOccupancy() int32 {
	if x != nil {
		return x.Occupancy
	}
	return 0
}

type PresenceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"` // 始终是精确频道
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`   // "join" | "leave"
	Info          *PresenceInfo          `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Gen           uint64                 `protobuf:"varint,4,opt,name=gen,proto3" json:"gen,omitempty"` // OccupancyGen
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceEvent) Reset() {
	*x = PresenceEvent{}
	mi := &file_client_v2_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceEvent) ProtoMessage() {}

func (x *PresenceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceEvent.ProtoReflect.Descriptor instead.
func (*PresenceEvent) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{25}
}

func (x *PresenceEvent) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PresenceEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PresenceEvent) GetInfo() *PresenceInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *PresenceEvent) GetGen() uint64 {
	if x != nil {
		return x.Gen
	}
	return 0
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_client_v2_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{26}
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_client_v2_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_client_v2_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_client_v2_service_proto_rawDescGZIP(), []int{27}
}

var File_client_v2_service_proto protoreflect.FileDescriptor

const file_client_v2_service_proto_rawDesc = "" +
	"\n" +
	"\x17client/v2/service.proto\x12\x15messageloop.client.v2\x1a\x16shared/v2/errors.proto\x1a\x15shared/v2/types.proto\"\x9b\x06\n" +
	"\x0eInboundMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x04R\x04time\x12:\n" +
	"\aconnect\x18\x03 \x01(\v2\x1e.messageloop.client.v2.ConnectH\x00R\aconnect\x12@\n" +
	"\tsubscribe\x18\x04 \x01(\v2 .messageloop.client.v2.SubscribeH\x00R\tsubscribe\x12F\n" +
	"\vunsubscribe\x18\x05 \x01(\v2\".messageloop.client.v2.UnsubscribeH\x00R\vunsubscribe\x12:\n" +
	"\apublish\x18\x06 \x01(\v2\x1e.messageloop.client.v2.PublishH\x00R\apublish\x12D\n" +
	"\vrpc_request\x18\a \x01(\v2!.messageloop.client.v2.RpcRequestH\x00R\n" +
	"rpcRequest\x12D\n" +
	"\vsub_refresh\x18\b \x01(\v2!.messageloop.client.v2.SubRefreshH\x00R\n" +
	"subRefresh\x12M\n" +
	"\x0esurvey_request\x18\t \x01(\v2$.messageloop.client.v2.SurveyRequestH\x00R\rsurveyRequest\x12G\n" +
	"\fsurvey_reply\x18\n" +
	" \x01(\v2\".messageloop.client.v2.SurveyReplyH\x00R\vsurveyReply\x121\n" +
	"\x04ping\x18\v \x01(\v2\x1b.messageloop.client.v2.PingH\x00R\x04ping\x121\n" +
	"\x04pong\x18\f \x01(\v2\x1b.messageloop.client.v2.PongH\x00R\x04pong\x12M\n" +
	"\x0epresence_query\x18\r \x01(\v2$.messageloop.client.v2.PresenceQueryH\x00R\rpresenceQueryB\n" +
	"\n" +
	"\benvelope\"\xaa\t\n" +
	"\x0fOutboundMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x04R\x04time\x124\n" +
	"\x05error\x18\x03 \x01(\v2\x1c.messageloop.shared.v2.ErrorH\x00R\x05error\x12@\n" +
	"\tconnected\x18\x04 \x01(\v2 .messageloop.client.v2.ConnectedH\x00R\tconnected\x12J\n" +
	"\rsubscribe_ack\x18\x05 \x01(\v2#.messageloop.client.v2.SubscribeAckH\x00R\fsubscribeAck\x12P\n" +
	"\x0funsubscribe_ack\x18\x06 \x01(\v2%.messageloop.client.v2.UnsubscribeAckH\x00R\x0eunsubscribeAck\x12D\n" +
	"\vpublish_ack\x18\a \x01(\v2!.messageloop.client.v2.PublishAckH\x00R\n" +
	"publishAck\x12F\n" +
	"\vpublication\x18\b \x01(\v2\".messageloop.client.v2.PublicationH\x00R\vpublication\x12S\n" +
	"\x10recover_complete\x18\t \x01(\v2&.messageloop.client.v2.RecoverCompleteH\x00R\x0frecoverComplete\x12>\n" +
	"\trpc_reply\x18\n" +
	" \x01(\v2\x1f.messageloop.client.v2.RpcReplyH\x00R\brpcReply\x12N\n" +
	"\x0fsub_refresh_ack\x18\v \x01(\v2$.messageloop.client.v2.SubRefreshAckH\x00R\rsubRefreshAck\x12M\n" +
	"\x0esurvey_request\x18\f \x01(\v2$.messageloop.client.v2.SurveyRequestH\x00R\rsurveyRequest\x12G\n" +
	"\fsurvey_reply\x18\r \x01(\v2\".messageloop.client.v2.SurveyReplyH\x00R\vsurveyReply\x12J\n" +
	"\rsurvey_result\x18\x0e \x01(\v2#.messageloop.client.v2.SurveyResultH\x00R\fsurveyResult\x12E\n" +
	"\bpresence\x18\x0f \x01(\v2'.messageloop.client.v2.PresenceSnapshotH\x00R\bpresence\x12M\n" +
	"\x0epresence_event\x18\x10 \x01(\v2$.messageloop.client.v2.PresenceEventH\x00R\rpresenceEvent\x121\n" +
	"\x04ping\x18\x11 \x01(\v2\x1b.messageloop.client.v2.PingH\x00R\x04ping\x121\n" +
	"\x04pong\x18\x12 \x01(\v2\x1b.messageloop.client.v2.PongH\x00R\x04pongB\n" +
	"\n" +
	"\benvelope\"\xf5\x01\n" +
	"\aConnect\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vclient_type\x18\x02 \x01(\tR\n" +
	"clientType\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12I\n" +
	"\rsubscriptions\x18\x05 \x03(\v2#.messageloop.client.v2.SubscriptionR\rsubscriptions\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04caps\x18\a \x03(\tR\x04caps\"\xd7\x01\n" +
	"\tConnected\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12I\n" +
	"\rsubscriptions\x18\x02 \x03(\v2#.messageloop.client.v2.SubscriptionR\rsubscriptions\x12\x18\n" +
	"\aresumed\x18\x03 \x01(\bR\aresumed\x12!\n" +
	"\fstream_epoch\x18\x04 \x01(\tR\vstreamEpoch\x12#\n" +
	"\raccepted_caps\x18\x05 \x03(\tR\facceptedCaps\"\xc5\x01\n" +
	"\fSubscription\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x1c\n" +
	"\tephemeral\x18\x02 \x01(\bR\tephemeral\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x18\n" +
	"\arecover\x18\x04 \x01(\bR\arecover\x127\n" +
	"\x06cursor\x18\x05 \x01(\v2\x1f.messageloop.shared.v2.PositionR\x06cursor\x12\x14\n" +
	"\x05fresh\x18\x06 \x01(\bR\x05fresh\"V\n" +
	"\tSubscribe\x12I\n" +
	"\rsubscriptions\x18\x01 \x03(\v2#.messageloop.client.v2.SubscriptionR\rsubscriptions\"\xb4\x02\n" +
	"\fSubscribeAck\x12I\n" +
	"\rsubscriptions\x18\x01 \x03(\v2#.messageloop.client.v2.SubscriptionR\rsubscriptions\x12=\n" +
	"\arecover\x18\x02 \x01(\x0e2#.messageloop.client.v2.RecoverStateR\arecover\x12!\n" +
	"\fstream_epoch\x18\x03 \x01(\tR\vstreamEpoch\x12C\n" +
	"\bpresence\x18\x04 \x03(\v2'.messageloop.client.v2.PresenceSnapshotR\bpresence\x122\n" +
	"\x05error\x18\x05 \x01(\v2\x1c.messageloop.shared.v2.ErrorR\x05error\"X\n" +
	"\vUnsubscribe\x12I\n" +
	"\rsubscriptions\x18\x01 \x03(\v2#.messageloop.client.v2.SubscriptionR\rsubscriptions\"[\n" +
	"\x0eUnsubscribeAck\x12I\n" +
	"\rsubscriptions\x18\x01 \x03(\v2#.messageloop.client.v2.SubscriptionR\rsubscriptions\"\x8d\x02\n" +
	"\x0fRecoverComplete\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12;\n" +
	"\bposition\x18\x02 \x01(\v2\x1f.messageloop.shared.v2.PositionR\bposition\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated\x12\x10\n" +
	"\x03gap\x18\x04 \x01(\bR\x03gap\x12?\n" +
	"\n" +
	"gap_reason\x18\x05 \x01(\x0e2 .messageloop.shared.v2.GapReasonR\tgapReason\x122\n" +
	"\x05error\x18\x06 \x01(\v2\x1c.messageloop.shared.v2.ErrorR\x05error\"\xf7\x01\n" +
	"\aPublish\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x128\n" +
	"\apayload\x18\x02 \x01(\v2\x1e.messageloop.shared.v2.PayloadR\apayload\x12;\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1f.messageloop.shared.v2.MetadataR\bmetadata\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x1c\n" +
	"\ttransient\x18\x05 \x01(\bR\ttransient\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\"Y\n" +
	"\n" +
	"PublishAck\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\bposition\x18\x02 \x01(\v2\x1f.messageloop.shared.v2.PositionR\bposition\"\xff\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12;\n" +
	"\bposition\x18\x03 \x01(\v2\x1f.messageloop.shared.v2.PositionR\bposition\x128\n" +
	"\apayload\x18\x04 \x01(\v2\x1e.messageloop.shared.v2.PayloadR\apayload\x12;\n" +
	"\bmetadata\x18\x05 \x01(\v2\x1f.messageloop.shared.v2.MetadataR\bmetadata\x12\x16\n" +
	"\x06replay\x18\x06 \x01(\bR\x06replay\"I\n" +
	"\vPublication\x12:\n" +
	"\bmessages\x18\x01 \x03(\v2\x1e.messageloop.client.v2.MessageR\bmessages\"\xb5\x01\n" +
	"\n" +
	"RpcRequest\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x128\n" +
	"\apayload\x18\x03 \x01(\v2\x1e.messageloop.shared.v2.PayloadR\apayload\x12;\n" +
	"\bmetadata\x18\x04 \x01(\v2\x1f.messageloop.shared.v2.MetadataR\bmetadata\"\xd4\x01\n" +
	"\bRpcReply\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\apayload\x18\x02 \x01(\v2\x1e.messageloop.shared.v2.PayloadR\apayload\x12;\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1f.messageloop.shared.v2.MetadataR\bmetadata\x122\n" +
	"\x05error\x18\x04 \x01(\v2\x1c.messageloop.shared.v2.ErrorR\x05error\"(\n" +
	"\n" +
	"SubRefresh\x12\x1a\n" +
	"\bchannels\x18\x01 \x03(\tR\bchannels\"\x0f\n" +
	"\rSubRefreshAck\"\xde\x01\n" +
	"\rSurveyRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\apayload\x18\x02 \x01(\v2\x1e.messageloop.shared.v2.PayloadR\apayload\x12;\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1f.messageloop.shared.v2.MetadataR\bmetadata\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x05R\ttimeoutMs\"\xd7\x01\n" +
	"\vSurveyReply\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\apayload\x18\x02 \x01(\v2\x1e.messageloop.shared.v2.PayloadR\apayload\x12;\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1f.messageloop.shared.v2.MetadataR\bmetadata\x122\n" +
	"\x05error\x18\x04 \x01(\v2\x1c.messageloop.shared.v2.ErrorR\x05error\"\xba\x01\n" +
	"\fSurveyResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12=\n" +
	"\aanswers\x18\x03 \x03(\v2#.messageloop.client.v2.SurveyAnswerR\aanswers\x122\n" +
	"\x05error\x18\x04 \x01(\v2\x1c.messageloop.shared.v2.ErrorR\x05error\"\xd8\x01\n" +
	"\fSurveyAnswer\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x128\n" +
	"\apayload\x18\x02 \x01(\v2\x1e.messageloop.shared.v2.PayloadR\apayload\x12;\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1f.messageloop.shared.v2.MetadataR\bmetadata\x122\n" +
	"\x05error\x18\x04 \x01(\v2\x1c.messageloop.shared.v2.ErrorR\x05error\")\n" +
	"\rPresenceQuery\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\"\x86\x01\n" +
	"\fPresenceInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12!\n" +
	"\fconnected_at\x18\x04 \x01(\x03R\vconnectedAt\"\xa7\x01\n" +
	"\x10PresenceSnapshot\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12=\n" +
	"\aclients\x18\x02 \x03(\v2#.messageloop.client.v2.PresenceInfoR\aclients\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated\x12\x1c\n" +
	"\toccupancy\x18\x04 \x01(\x05R\toccupancy\"\x8c\x01\n" +
	"\rPresenceEvent\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x127\n" +
	"\x04info\x18\x03 \x01(\v2#.messageloop.client.v2.PresenceInfoR\x04info\x12\x10\n" +
	"\x03gen\x18\x04 \x01(\x04R\x03gen\"\x06\n" +
	"\x04Ping\"\x06\n" +
	"\x04Pong*\x95\x01\n" +
	"\fRecoverState\x12\x1d\n" +
	"\x19RECOVER_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RECOVER_STATE_NONE\x10\x01\x12\x19\n" +
	"\x15RECOVER_STATE_PENDING\x10\x02\x12\x19\n" +
	"\x15RECOVER_STATE_SKIPPED\x10\x03\x12\x18\n" +
	"\x14RECOVER_STATE_FAILED\x10\x042v\n" +
	"\x12MessageLoopService\x12`\n" +
	"\vMessageLoop\x12%.messageloop.client.v2.InboundMessage\x1a&.messageloop.client.v2.OutboundMessage(\x010\x01BIZGgithub.com/messageloopio/messageloop/shared/genproto/client/v2;clientv2b\x06proto3"

var (
	file_client_v2_service_proto_rawDescOnce sync.Once
	file_client_v2_service_proto_rawDescData []byte
)

func file_client_v2_service_proto_rawDescGZIP() []byte {
	file_client_v2_service_proto_rawDescOnce.Do(func() {
		file_client_v2_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_v2_service_proto_rawDesc), len(file_client_v2_service_proto_rawDesc)))
	})
	return file_client_v2_service_proto_rawDescData
}

var file_client_v2_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_client_v2_service_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_client_v2_service_proto_goTypes = []any{
	(RecoverState)(0),        // 0: messageloop.client.v2.RecoverState
	(*InboundMessage)(nil),   // 1: messageloop.client.v2.InboundMessage
	(*OutboundMessage)(nil),  // 2: messageloop.client.v2.OutboundMessage
	(*Connect)(nil),          // 3: messageloop.client.v2.Connect
	(*Connected)(nil),        // 4: messageloop.client.v2.Connected
	(*Subscription)(nil),     // 5: messageloop.client.v2.Subscription
	(*Subscribe)(nil),        // 6: messageloop.client.v2.Subscribe
	(*SubscribeAck)(nil),     // 7: messageloop.client.v2.SubscribeAck
	(*Unsubscribe)(nil),      // 8: messageloop.client.v2.Unsubscribe
	(*UnsubscribeAck)(nil),   // 9: messageloop.client.v2.UnsubscribeAck
	(*RecoverComplete)(nil),  // 10: messageloop.client.v2.RecoverComplete
	(*Publish)(nil),          // 11: messageloop.client.v2.Publish
	(*PublishAck)(nil),       // 12: messageloop.client.v2.PublishAck
	(*Message)(nil),          // 13: messageloop.client.v2.Message
	(*Publication)(nil),      // 14: messageloop.client.v2.Publication
	(*RpcRequest)(nil),       // 15: messageloop.client.v2.RpcRequest
	(*RpcReply)(nil),         // 16: messageloop.client.v2.RpcReply
	(*SubRefresh)(nil),       // 17: messageloop.client.v2.SubRefresh
	(*SubRefreshAck)(nil),    // 18: messageloop.client.v2.SubRefreshAck
	(*SurveyRequest)(nil),    // 19: messageloop.client.v2.SurveyRequest
	(*SurveyReply)(nil),      // 20: messageloop.client.v2.SurveyReply
	(*SurveyResult)(nil),     // 21: messageloop.client.v2.SurveyResult
	(*SurveyAnswer)(nil),     // 22: messageloop.client.v2.SurveyAnswer
	(*PresenceQuery)(nil),    // 23: messageloop.client.v2.PresenceQuery
	(*PresenceInfo)(nil),     // 24: messageloop.client.v2.PresenceInfo
	(*PresenceSnapshot)(nil), // 25: messageloop.client.v2.PresenceSnapshot
	(*PresenceEvent)(nil),    // 26: messageloop.client.v2.PresenceEvent
	(*Ping)(nil),             // 27: messageloop.client.v2.Ping
	(*Pong)(nil),             // 28: messageloop.client.v2.Pong
	(*v2.Error)(nil),         // 29: messageloop.shared.v2.Error
	(*v2.Position)(nil),      // 30: messageloop.shared.v2.Position
	(v2.GapReason)(0),        // 31: messageloop.shared.v2.GapReason
	(*v2.Payload)(nil),       // 32: messageloop.shared.v2.Payload
	(*v2.Metadata)(nil),      // 33: messageloop.shared.v2.Metadata
}
var file_client_v2_service_proto_depIdxs = []int32{
	3,  // 0: messageloop.client.v2.InboundMessage.connect:type_name -> messageloop.client.v2.Connect
	6,  // 1: messageloop.client.v2.InboundMessage.subscribe:type_name -> messageloop.client.v2.Subscribe
	8,  // 2: messageloop.client.v2.InboundMessage.unsubscribe:type_name -> messageloop.client.v2.Unsubscribe
	11, // 3: messageloop.client.v2.InboundMessage.publish:type_name -> messageloop.client.v2.Publish
	15, // 4: messageloop.client.v2.InboundMessage.rpc_request:type_name -> messageloop.client.v2.RpcRequest
	17, // 5: messageloop.client.v2.InboundMessage.sub_refresh:type_name -> messageloop.client.v2.SubRefresh
	19, // 6: messageloop.client.v2.InboundMessage.survey_request:type_name -> messageloop.client.v2.SurveyRequest
	20, // 7: messageloop.client.v2.InboundMessage.survey_reply:type_name -> messageloop.client.v2.SurveyReply
	27, // 8: messageloop.client.v2.InboundMessage.ping:type_name -> messageloop.client.v2.Ping
	28, // 9: messageloop.client.v2.InboundMessage.pong:type_name -> messageloop.client.v2.Pong
	23, // 10: messageloop.client.v2.InboundMessage.presence_query:type_name -> messageloop.client.v2.PresenceQuery
	29, // 11: messageloop.client.v2.OutboundMessage.error:type_name -> messageloop.shared.v2.Error
	4,  // 12: messageloop.client.v2.OutboundMessage.connected:type_name -> messageloop.client.v2.Connected
	7,  // 13: messageloop.client.v2.OutboundMessage.subscribe_ack:type_name -> messageloop.client.v2.SubscribeAck
	9,  // 14: messageloop.client.v2.OutboundMessage.unsubscribe_ack:type_name -> messageloop.client.v2.UnsubscribeAck
	12, // 15: messageloop.client.v2.OutboundMessage.publish_ack:type_name -> messageloop.client.v2.PublishAck
	14, // 16: messageloop.client.v2.OutboundMessage.publication:type_name -> messageloop.client.v2.Publication
	10, // 17: messageloop.client.v2.OutboundMessage.recover_complete:type_name -> messageloop.client.v2.RecoverComplete
	16, // 18: messageloop.client.v2.OutboundMessage.rpc_reply:type_name -> messageloop.client.v2.RpcReply
	18, // 19: messageloop.client.v2.OutboundMessage.sub_refresh_ack:type_name -> messageloop.client.v2.SubRefreshAck
	19, // 20: messageloop.client.v2.OutboundMessage.survey_request:type_name -> messageloop.client.v2.SurveyRequest
	20, // 21: messageloop.client.v2.OutboundMessage.survey_reply:type_name -> messageloop.client.v2.SurveyReply
	21, // 22: messageloop.client.v2.OutboundMessage.survey_result:type_name -> messageloop.client.v2.SurveyResult
	25, // 23: messageloop.client.v2.OutboundMessage.presence:type_name -> messageloop.client.v2.PresenceSnapshot
	26, // 24: messageloop.client.v2.OutboundMessage.presence_event:type_name -> messageloop.client.v2.PresenceEvent
	27, // 25: messageloop.client.v2.OutboundMessage.ping:type_name -> messageloop.client.v2.Ping
	28, // 26: messageloop.client.v2.OutboundMessage.pong:type_name -> messageloop.client.v2.Pong
	5,  // 27: messageloop.client.v2.Connect.subscriptions:type_name -> messageloop.client.v2.Subscription
	5,  // 28: messageloop.client.v2.Connected.subscriptions:type_name -> messageloop.client.v2.Subscription
	30, // 29: messageloop.client.v2.Subscription.cursor:type_name -> messageloop.shared.v2.Position
	5,  // 30: messageloop.client.v2.Subscribe.subscriptions:type_name -> messageloop.client.v2.Subscription
	5,  // 31: messageloop.client.v2.SubscribeAck.subscriptions:type_name -> messageloop.client.v2.Subscription
	0,  // 32: messageloop.client.v2.SubscribeAck.recover:type_name -> messageloop.client.v2.RecoverState
	25, // 33: messageloop.client.v2.SubscribeAck.presence:type_name -> messageloop.client.v2.PresenceSnapshot
	29, // 34: messageloop.client.v2.SubscribeAck.error:type_name -> messageloop.shared.v2.Error
	5,  // 35: messageloop.client.v2.Unsubscribe.subscriptions:type_name -> messageloop.client.v2.Subscription
	5,  // 36: messageloop.client.v2.UnsubscribeAck.subscriptions:type_name -> messageloop.client.v2.Subscription
	30, // 37: messageloop.client.v2.RecoverComplete.position:type_name -> messageloop.shared.v2.Position
	31, // 38: messageloop.client.v2.RecoverComplete.gap_reason:type_name -> messageloop.shared.v2.GapReason
	29, // 39: messageloop.client.v2.RecoverComplete.error:type_name -> messageloop.shared.v2.Error
	32, // 40: messageloop.client.v2.Publish.payload:type_name -> messageloop.shared.v2.Payload
	33, // 41: messageloop.client.v2.Publish.metadata:type_name -> messageloop.shared.v2.Metadata
	30, // 42: messageloop.client.v2.PublishAck.position:type_name -> messageloop.shared.v2.Position
	30, // 43: messageloop.client.v2.Message.position:type_name -> messageloop.shared.v2.Position
	32, // 44: messageloop.client.v2.Message.payload:type_name -> messageloop.shared.v2.Payload
	33, // 45: messageloop.client.v2.Message.metadata:type_name -> messageloop.shared.v2.Metadata
	13, // 46: messageloop.client.v2.Publication.messages:type_name -> messageloop.client.v2.Message
	32, // 47: messageloop.client.v2.RpcRequest.payload:type_name -> messageloop.shared.v2.Payload
	33, // 48: messageloop.client.v2.RpcRequest.metadata:type_name -> messageloop.shared.v2.Metadata
	32, // 49: messageloop.client.v2.RpcReply.payload:type_name -> messageloop.shared.v2.Payload
	33, // 50: messageloop.client.v2.RpcReply.metadata:type_name -> messageloop.shared.v2.Metadata
	29, // 51: messageloop.client.v2.RpcReply.error:type_name -> messageloop.shared.v2.Error
	32, // 52: messageloop.client.v2.SurveyRequest.payload:type_name -> messageloop.shared.v2.Payload
	33, // 53: messageloop.client.v2.SurveyRequest.metadata:type_name -> messageloop.shared.v2.Metadata
	32, // 54: messageloop.client.v2.SurveyReply.payload:type_name -> messageloop.shared.v2.Payload
	33, // 55: messageloop.client.v2.SurveyReply.metadata:type_name -> messageloop.shared.v2.Metadata
	29, // 56: messageloop.client.v2.SurveyReply.error:type_name -> messageloop.shared.v2.Error
	22, // 57: messageloop.client.v2.SurveyResult.answers:type_name -> messageloop.client.v2.SurveyAnswer
	29, // 58: messageloop.client.v2.SurveyResult.error:type_name -> messageloop.shared.v2.Error
	32, // 59: messageloop.client.v2.SurveyAnswer.payload:type_name -> messageloop.shared.v2.Payload
	33, // 60: messageloop.client.v2.SurveyAnswer.metadata:type_name -> messageloop.shared.v2.Metadata
	29, // 61: messageloop.client.v2.SurveyAnswer.error:type_name -> messageloop.shared.v2.Error
	24, // 62: messageloop.client.v2.PresenceSnapshot.clients:type_name -> messageloop.client.v2.PresenceInfo
	24, // 63: messageloop.client.v2.PresenceEvent.info:type_name -> messageloop.client.v2.PresenceInfo
	1,  // 64: messageloop.client.v2.MessageLoopService.MessageLoop:input_type -> messageloop.client.v2.InboundMessage
	2,  // 65: messageloop.client.v2.MessageLoopService.MessageLoop:output_type -> messageloop.client.v2.OutboundMessage
	65, // [65:66] is the sub-list for method output_type
	64, // [64:65] is the sub-list for method input_type
	64, // [64:64] is the sub-list for extension type_name
	64, // [64:64] is the sub-list for extension extendee
	0,  // [0:64] is the sub-list for field type_name
}

func init() { file_client_v2_service_proto_init() }
func file_client_v2_service_proto_init() {
	if File_client_v2_service_proto != nil {
		return
	}
	file_client_v2_service_proto_msgTypes[0].OneofWrappers = []any{
		(*InboundMessage_Connect)(nil),
		(*InboundMessage_Subscribe)(nil),
		(*InboundMessage_Unsubscribe)(nil),
		(*InboundMessage_Publish)(nil),
		(*InboundMessage_RpcRequest)(nil),
		(*InboundMessage_SubRefresh)(nil),
		(*InboundMessage_SurveyRequest)(nil),
		(*InboundMessage_SurveyReply)(nil),
		(*InboundMessage_Ping)(nil),
		(*InboundMessage_Pong)(nil),
		(*InboundMessage_PresenceQuery)(nil),
	}
	file_client_v2_service_proto_msgTypes[1].OneofWrappers = []any{
		(*OutboundMessage_Error)(nil),
		(*OutboundMessage_Connected)(nil),
		(*OutboundMessage_SubscribeAck)(nil),
		(*OutboundMessage_UnsubscribeAck)(nil),
		(*OutboundMessage_PublishAck)(nil),
		(*OutboundMessage_Publication)(nil),
		(*OutboundMessage_RecoverComplete)(nil),
		(*OutboundMessage_RpcReply)(nil),
		(*OutboundMessage_SubRefreshAck)(nil),
		(*OutboundMessage_SurveyRequest)(nil),
		(*OutboundMessage_SurveyReply)(nil),
		(*OutboundMessage_SurveyResult)(nil),
		(*OutboundMessage_Presence)(nil),
		(*OutboundMessage_PresenceEvent)(nil),
		(*OutboundMessage_Ping)(nil),
		(*OutboundMessage_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_v2_service_proto_rawDesc), len(file_client_v2_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_v2_service_proto_goTypes,
		DependencyIndexes: file_client_v2_service_proto_depIdxs,
		EnumInfos:         file_client_v2_service_proto_enumTypes,
		MessageInfos:      file_client_v2_service_proto_msgTypes,
	}.Build()
	File_client_v2_service_proto = out.File
	file_client_v2_service_proto_goTypes = nil
	file_client_v2_service_proto_depIdxs = nil
}
