// @generated by protoc-gen-es v2.10.0 with parameter "target=ts,import_extension=none"
// @generated from file shared/v2/errors.proto (package messageloop.shared.v2, syntax proto3)
/* eslint-disable */

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file shared/v2/errors.proto.
 */
export const file_shared_v2_errors: GenFile = /*@__PURE__*/
  fileDesc("ChZzaGFyZWQvdjIvZXJyb3JzLnByb3RvEhVtZXNzYWdlbG9vcC5zaGFyZWQudjIiXwoFRXJyb3ISDAoEY29kZRgBIAEoCRIMCgR0eXBlGAIgASgJEg8KB21lc3NhZ2UYAyABKAkSKQoIbWV0YWRhdGEYBCABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0QklaR2dpdGh1Yi5jb20vbWVzc2FnZWxvb3Bpby9tZXNzYWdlbG9vcC9zaGFyZWQvZ2VucHJvdG8vc2hhcmVkL3YyO3NoYXJlZHYyYgZwcm90bzM", [file_google_protobuf_struct]);

/**
 * @generated from message messageloop.shared.v2.Error
 */
export type Error = Message<"messageloop.shared.v2.Error"> & {
  /**
   * Well-known string codes (not an enum). This is the single code table;
   * the Error Codes section of docs/protocol.md mirrors it and must stay in
   * sync. Grouped:
   *
   *   authentication/version:
   *     AUTH_REQUIRED (auth_error), AUTH_ERROR (auth_error),
   *     VERSION_UNSUPPORTED (version_error)
   *   request/permission:
   *     BAD_REQUEST (client_error for undecodable frames, request_error for
   *     invalid requests), PERMISSION_DENIED (acl_error),
   *     POLICY_DENIED (policy_error), PATTERN_NOT_ROUTABLE (request_error),
   *     RATE_LIMITED (rate_limit)
   *   proxy/RPC:
   *     NO_PROXY (request_error), PROXY_ERROR (proxy_error),
   *     RPC_TIMEOUT (timeout)
   *   recovery:
   *     RECOVER_FAILED (recover_error), RECOVER_SKIPPED (recover_error)
   *   survey top-level:
   *     SURVEY_DISABLED (policy_error),
   *     SURVEY_TOO_MANY_SUBSCRIBERS (survey_error)
   *   survey per-answer:
   *     SURVEY_FAILED (survey_error),
   *     SURVEY_ANSWER_TOO_LARGE (survey_error)
   *   server/transport:
   *     INTERNAL_ERROR (server_error), DISCONNECT_ERROR (transport_error)
   *
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string type = 2;
   */
  type: string;

  /**
   * @generated from field: string message = 3;
   */
  message: string;

  /**
   * @generated from field: google.protobuf.Struct metadata = 4;
   */
  metadata?: JsonObject;
};

/**
 * Describes the message messageloop.shared.v2.Error.
 * Use `create(ErrorSchema)` to create a new message.
 */
export const ErrorSchema: GenMessage<Error> = /*@__PURE__*/
  messageDesc(file_shared_v2_errors, 0);

